#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.2  $                                                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
MISC =                            \
        $(LIBDIR)\c0$(MODEL).obj  \
        $(LIBDIR)\c0f$(MODEL).obj

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
!include rules.mak

ASM = $(ASM)
AFLAGS = -m -mx -q -t -I$(INCLBASE)\rtlinc\common16

#############################################################################
# MISC explicit rules.                                                      #
#############################################################################
$(LIBDIR)\c0t.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__TINY__    $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0s.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__SMALL__   $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0c.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__COMPACT__ $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0m.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__MEDIUM__  $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0l.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__LARGE__   $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0h.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__HUGE__    $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0ft.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__TINY__    -d_DSSTACK_ $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0fs.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__SMALL__   -d_DSSTACK_ $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0fc.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__COMPACT__ -d_DSSTACK_ $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0fm.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__MEDIUM__  -d_DSSTACK_ $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0fl.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__LARGE__   -d_DSSTACK_ $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

$(LIBDIR)\c0fh.obj : c0.asm
        copy &&|
        $(AFLAGS)
|       tasm.cfg
        $(ASM) -d__HUGE__                $**, $(OBJDIR)\$.
        del tasm.cfg
        copy $(OBJDIR)\$. $(LIBDIR)

