#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------
# This example reads and writes to OWL.INI to let you enable/disable OWL
# diagnostics.  The diagnostic settings for an application are read from
# OWL.INI when the application loads.  In order to allow OWL applications
# that use the OWL DLL to re-start with new diagnostic settings, this 
# utility should not be built using the DLL version of OWL. Doing so would
# prevent the DLL from being reloaded when the applications re-start
# and would result in the new diagnostic settings to be ignored.
#

MODELS=l                      #Allowable memory models
SYSTEM=WIN16                  #Toolhelp only available in 16-bit currently
MODEL=l                       #Default to only allowable model
EXERES=diagxprt


OBJEXE=diagxprt.obj cback.obj setup.obj toolhelp.obj
!include $(BCEXAMPLEDIR)\owlmake.gen

