#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\commondg\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = commondg
CPCH    = -Hc -H"windows.h" -H=commondg.csm
OBJEXE  = commondg.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          filedlg.obj finddlg.obj optdlg.obj printdlg.obj

!include $(BCEXAMPLEDIR)\makefile.gen
