#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1996 by Borland International
#----------------------------------------------------------------------------

EXERES=filebrow
MODELS=ldf
!include $(BCEXAMPLEDIR)\owlmake.gen

