#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\iathread\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = iathread
CPCH    = -Hc -H"windows.h" -H=iathread.csm
OBJEXE  = iathread.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          mdichild.obj priority.obj

!include $(BCEXAMPLEDIR)\makefile.gen
