#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES=bmpview
MODELS=mldf
!include $(BCEXAMPLEDIR)\owlmake.gen

