//----------------------------------------------------------------------------
// ObjectWindows - (C) Copyright 1991, 1996 by Borland International
//   calldemo.h
//
//----------------------------------------------------------------------------

#define ICON_1	1
#define CALLDEMODLG            1
#define IDC_LANGUAGE         101
#define IDC_ENGLISH          102
#define IDC_FRENCH           103
#define IDC_GERMAN           104
#define IDC_LOCALE           105
#define IDC_CLOCALE          106
#define IDC_USLOCALE         107
#define IDC_UKLOCALE         108
#define IDC_FRALOCALE        109
#define IDC_GERLOCALE        110
#define IDC_CLASSIFICATION   111

#define IDS_ISALNUM          200
#define IDS_ISALPHA          201
#define IDS_ISASCII          202
#define IDS_ISCNTRL          203
#define IDS_ISDIGIT          204
#define IDS_ISGRAPH          205
#define IDS_ISLOWER          206
#define IDS_ISPRINT          207
#define IDS_ISPUNCT          208
#define IDS_ISSPACE          209
#define IDS_ISUPPER          210
#define IDS_ISXDIGIT         211
