#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1993, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

# Help files
#
HLP= english french german
HLP_= english.rtf french.rtf german.rtf intldemo.hh

# DLLs
#
DLLRES = dummyDLL
OBJDLL =
DLLALL = apiger.dll apifra.dll apieng.dll
DLLMAKE= $(APIGER) $(APIFRA) $(APIENG)
APIGER = $(DLLRULE:dummyDLL=apiger)
APIFRA = $(DLLRULE:dummyDLL=apifra)
APIENG = $(DLLRULE:dummyDLL=apieng)

# EXEs
#
EXERES = dummyEXE
EXEALL = intldemo.exe calldemo.exe
EXEMAKE= $(INTLDEMO) $(CALLDEMO)
__INTL = $(EXERULE:dummyEXE=intldemo)
INTLDEMO= $(__INTL:intldemo.obj=intldemo.obj filelist.obj)
CALLDEMO= $(EXERULE:dummyEXE=calldemo)

!include $(BCEXAMPLEDIR)\owlocfmk.gen

CFLAGS = $(CFLAGS) -D__USELOCALES__
