// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.0.1.0.1.0  $
// File generated on 1/29/2002 1:29:46 PM from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\PROGRA~1\MICROS~4\Office10\FPEDITAX.DLL (1)
// LIBID: {7577AE81-4416-11CE-9C34-524153480000}
// LCID: 0
// Helpfile: C:\PROGRA~1\MICROS~4\Office10\VBAFPD10.CHM
// HelpString: Microsoft FrontPage 5.0 Page Object Reference Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
// Parent TypeLibrary:
//   (0) v5.0 FrontPage, (c:\program files\microsoft office\office10\frontpg.exe)
// ************************************************************************ //
#ifndef   FrontPageEditor_XP_srvrH
#define   FrontPageEditor_XP_srvrH

#pragma option push -b -w-inl

#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "FrontPageEditor_XP.h"
namespace Frontpageeditor_xp
{

// *********************************************************************//
// HelpString: Microsoft FrontPage 5.0 Page Object Reference Library
// Version:    5.0
// *********************************************************************//

};     // namespace Frontpageeditor_xp

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Frontpageeditor_xp;
#endif

#pragma option pop

#endif // FrontPageEditor_XP_srvrH
