// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.21  $
// File generated on 1/28/2002 8:27:06 AM from Type Library described below.

// ************************************************************************  //
// Type Lib: c:\program files\microsoft office\office\graph9.olb (1)
// LIBID: {00020802-0000-0000-C000-000000000046}
// LCID: 0
// Helpfile: c:\program files\microsoft office\office\VBAGRP9.CHM
// HelpString: Microsoft Graph 9.0 Object Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
//   (2) v2.1 Office, (C:\Program Files\Microsoft Office\Office\MSO9.DLL)
// ************************************************************************ //
#ifndef   Graph_2k_srvrH
#define   Graph_2k_srvrH

#pragma option push -b -w-inl

#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "Office_2k.h"

#include "Graph_2k.h"
namespace Graph_2k
{

// *********************************************************************//
// HelpString: Microsoft Graph 9.0 Object Library
// Version:    1.3
// *********************************************************************//

};     // namespace Graph_2k

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Graph_2k;
#endif

#pragma option pop

#endif // Graph_2k_srvrH
