// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.0.1.3  $
// File generated on 1/24/2000 09:46:28 AM from Type Library described below.

// ************************************************************************ //
// Type Lib: d:\tlbgen\rampage\typelib\TypeLibraries\GRAPH9.olb (1)
// IID\LCID: {00020802-0000-0000-C000-000000000046}\0
// Helpfile: d:\tlbgen\rampage\typelib\TypeLibraries\VBAGRP9.CHM
// DepndLst: 
//   (1) v2.0 stdole, (D:\WINNT\System32\stdole2.tlb)
//   (2) v2.1 Office, (D:\msof2k\Office\mso9.dll)
//   (3) v4.0 StdVCL, (D:\tlbgen\rampage\typelib\typelibraries\testing\stdvcl40.tlb)
// ************************************************************************ //
#ifndef   __Graph_2K_SRVR_h__
#define   __Graph_2K_SRVR_h__

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0500)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "Office_2K.h"

#include "Graph_2K.h"
namespace Graph_2k
{

// *********************************************************************//
// HelpString: Microsoft Graph 9.0 Object Library
// Version:    1.3
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TGlobal
// Help String      : 
// Default Interface: _Global
// Def. Intf. Object: _GlobalPtr
// Def. Intf. DISP? : Yes
// Event   Interface: 
// TypeFlags        : (27) AppObject CanCreate Predeclid Hidden
// *********************************************************************//
class PACKAGE TGlobal : public Oleserver::TOleServer
{
  _GlobalPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TGlobal(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  _GlobalPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_GlobalPtr intf);


  /*CoClassWriteArrayPropMethods*/
  Graph_2k::GraphApplicationPtr __fastcall Get_Application(void)
  {
    return GetDefaultInterface()->get_Application();
  }

  Graph_2k::XlCreator __fastcall Get_Creator(void)
  {
    return GetDefaultInterface()->get_Creator();
  }

  Graph_2k::GraphApplicationPtr __fastcall Get_Parent(void)
  {
    return GetDefaultInterface()->get_Parent();
  }

  Office_2k::CommandBarsPtr __fastcall Get_CommandBars(void)
  {
    return GetDefaultInterface()->get_CommandBars();
  }

  /*CoClassWriteMethods*/
  /*CoClassWriteProperties*/
  __property Graph_2k::GraphApplicationPtr Application={ read=Get_Application }; // 0, Yes
  __property Graph_2k::XlCreator Creator={ read=Get_Creator }; // 0, No
  __property Graph_2k::GraphApplicationPtr Parent={ read=Get_Parent }; // 0, Yes
  __property Office_2k::CommandBarsPtr CommandBars={ read=Get_CommandBars }; // 0, Yes
  /*CoClassWriteProperties*/
};

};     // namespace Graph_2k

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Graph_2k;
#endif

#pragma option pop

#endif // __Graph_2K_SRVR_h__
