// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.0.2.3  $
// File generated on 1/24/2000 9:50:17 AM from Type Library described below.

// ************************************************************************ //
// Type Lib: D:\Program Files\Microsoft Office\Office\MSO97.DLL (1)
// IID\LCID: {2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}\0
// Helpfile: D:\Program Files\Microsoft Office\Office\vbaoff8.hlp
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
// Parent TypeLibrary:
//   (0) v1.2 Graph, (g:\rampage\typelib\TypeLibraries\GRAPH8.olb)
// ************************************************************************ //
#ifndef   __Office_97_SRVR_h__
#define   __Office_97_SRVR_h__

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0500)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "Office_97.h"
namespace Office_97
{

// *********************************************************************//
// HelpString: Microsoft Office 8.0 Object Library
// Version:    2.0
// *********************************************************************//

};     // namespace Office_97

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Office_97;
#endif

#pragma option pop

#endif // __Office_97_SRVR_h__
