// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.21  $
// File generated on 1/28/2002 7:56:10 AM from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files\Microsoft Office\office97\Office\MSO97.DLL (2)
// LIBID: {2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}
// LCID: 0
// Helpfile: C:\Program Files\Microsoft Office\office97\Office\vbaoff8.hlp
// HelpString: Microsoft Office 8.0 Object Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
// Parent TypeLibrary:
//   (0) v1.2 Excel, (c:\program files\microsoft office\office\excel8.olb)
// ************************************************************************ //
#ifndef   Office_97_SRVRH
#define   Office_97_SRVRH

#pragma option push -b -w-inl

#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "Office_97.h"
namespace Office_97
{

// *********************************************************************//
// HelpString: Microsoft Office 8.0 Object Library
// Version:    2.0
// *********************************************************************//

};     // namespace Office_97

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Office_97;
#endif

#pragma option pop

#endif // Office_97_SRVRH
