// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.21  $
// File generated on 1/28/2002 8:27:22 AM from Type Library described below.

// ************************************************************************  //
// Type Lib: c:\program files\microsoft office\office\msoutl9.olb (1)
// LIBID: {00062FFF-0000-0000-C000-000000000046}
// LCID: 0
// Helpfile: c:\program files\microsoft office\office\VBAOUTL9.CHM
// HelpString: Microsoft Outlook 9.0 Object Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
//   (2) v2.1 Office, (C:\Program Files\Microsoft Office\Office\MSO9.DLL)
// ************************************************************************ //
#ifndef   Outlook_2k_srvrH
#define   Outlook_2k_srvrH

#pragma option push -b -w-inl

#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "Office_2k.h"

#include "Outlook_2k.h"
namespace Outlook_2k
{

// *********************************************************************//
// HelpString: Microsoft Outlook 9.0 Object Library
// Version:    9.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOutlookApplication
// Help String      : 
// Default Interface: _Application
// Def. Intf. Object: _ApplicationPtr
// Def. Intf. DISP? : No
// Event   Interface: ApplicationEvents
// TypeFlags        : (11) AppObject CanCreate Predeclid
// *********************************************************************//
typedef void __fastcall (__closure * TOutlookApplicationItemSend)(System::TObject * Sender, 
                                                                  LPDISPATCH Item/*[in]*/, 
                                                                  VARIANT_BOOL* Cancel/*[in]*/);
typedef void __fastcall (__closure * TOutlookApplicationReminder)(System::TObject * Sender, 
                                                                  LPDISPATCH Item/*[in]*/);
typedef void __fastcall (__closure * TOutlookApplicationOptionsPagesAdd)(System::TObject * Sender, 
                                                                         Outlook_2k::PropertyPages* Pages/*[in]*/);

class PACKAGE TOutlookApplication : public Oleserver::TOleServer
{
  _ApplicationPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOutlookApplication(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  _ApplicationPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ApplicationPtr intf);

  virtual void __fastcall InvokeEvent(int DispID, Oleserver::TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
// StdProp:
  Outlook_2k::_ApplicationPtr __fastcall get_Application(void)
  {
    return GetDefaultInterface()->get_Application();
  }

// StdProp:TOleEnum
  Outlook_2k::OlObjectClass __fastcall get_Class(void)
  {
    return GetDefaultInterface()->get_Class();
  }

// StdProp:
  Outlook_2k::_NameSpacePtr __fastcall get_Session(void)
  {
    return GetDefaultInterface()->get_Session();
  }

// StdProp:IDispatch
  LPDISPATCH __fastcall get_Parent(void)
  {
    return GetDefaultInterface()->get_Parent();
  }

// StdProp:
  Office_2k::AssistantPtr __fastcall get_Assistant(void)
  {
    return GetDefaultInterface()->get_Assistant();
  }

// StdProp:WideString
  BSTR __fastcall get_Name(void)
  {
    return GetDefaultInterface()->get_Name();
  }

// StdProp:WideString
  BSTR __fastcall get_Version(void)
  {
    return GetDefaultInterface()->get_Version();
  }

// StdProp:
  Office_2k::COMAddInsPtr __fastcall get_COMAddIns(void)
  {
    return GetDefaultInterface()->get_COMAddIns();
  }

// StdProp:
  Outlook_2k::_ExplorersPtr __fastcall get_Explorers(void)
  {
    return GetDefaultInterface()->get_Explorers();
  }

// StdProp:
  Outlook_2k::_InspectorsPtr __fastcall get_Inspectors(void)
  {
    return GetDefaultInterface()->get_Inspectors();
  }

// StdProp:
  Office_2k::LanguageSettingsPtr __fastcall get_LanguageSettings(void)
  {
    return GetDefaultInterface()->get_LanguageSettings();
  }

// StdProp:WideString
  BSTR __fastcall get_ProductCode(void)
  {
    return GetDefaultInterface()->get_ProductCode();
  }

// StdProp:
  Office_2k::AnswerWizardPtr __fastcall get_AnswerWizard(void)
  {
    return GetDefaultInterface()->get_AnswerWizard();
  }

// StdProp:TOleEnum
  Office_2k::MsoFeatureInstall __fastcall get_FeatureInstall(void)
  {
    return GetDefaultInterface()->get_FeatureInstall();
  }

// StdProp:TOleEnum
  void __fastcall set_FeatureInstall(Office_2k::MsoFeatureInstall FeatureInstall/*[in]*/)
  {
    GetDefaultInterface()->set_FeatureInstall(FeatureInstall/*[in]*/);
  }

  /*CoClassWriteMethods*/
  Outlook_2k::_ExplorerPtr __fastcall ActiveExplorer(void)
  {
    return GetDefaultInterface()->ActiveExplorer();
  }

  Outlook_2k::_InspectorPtr __fastcall ActiveInspector(void)
  {
    return GetDefaultInterface()->ActiveInspector();
  }

  LPDISPATCH __fastcall CreateItem(Outlook_2k::OlItemType ItemType/*[in]*/)
  {
    return GetDefaultInterface()->CreateItem(ItemType/*[in]*/);
  }

  LPDISPATCH __fastcall CreateItemFromTemplate(BSTR TemplatePath/*[in]*/, 
                                               VARIANT InFolder/*[in,opt]*/)
  {
    return GetDefaultInterface()->CreateItemFromTemplate(TemplatePath/*[in]*/, InFolder/*[in,opt]*/);
  }

  LPDISPATCH __fastcall CreateObject(BSTR ObjectName/*[in]*/)
  {
    return GetDefaultInterface()->CreateObject(ObjectName/*[in]*/);
  }

  Outlook_2k::_NameSpacePtr __fastcall GetNamespace(BSTR Type/*[in]*/)
  {
    return GetDefaultInterface()->GetNamespace(Type/*[in]*/);
  }

  void __fastcall Quit(void)
  {
    GetDefaultInterface()->Quit();
  }

  LPDISPATCH __fastcall ActiveWindow(void)
  {
    return GetDefaultInterface()->ActiveWindow();
  }

  /*CoClassWriteProperties*/
  __property Outlook_2k::_ApplicationPtr Application={ read=get_Application }; // 0, Yes
  __property Outlook_2k::OlObjectClass Class={ read=get_Class }; // 0, No
  __property Outlook_2k::_NameSpacePtr Session={ read=get_Session }; // 0, Yes
  __property LPDISPATCH Parent={ read=get_Parent }; // 0, No
  __property Office_2k::AssistantPtr Assistant={ read=get_Assistant }; // 0, Yes
  __property BSTR Name={ read=get_Name }; // 0, No
  __property BSTR Version={ read=get_Version }; // 0, No
  __property Office_2k::COMAddInsPtr COMAddIns={ read=get_COMAddIns }; // 0, Yes
  __property Outlook_2k::_ExplorersPtr Explorers={ read=get_Explorers }; // 0, Yes
  __property Outlook_2k::_InspectorsPtr Inspectors={ read=get_Inspectors }; // 0, Yes
  __property Office_2k::LanguageSettingsPtr LanguageSettings={ read=get_LanguageSettings }; // 0, Yes
  __property BSTR ProductCode={ read=get_ProductCode }; // 0, No
  __property Office_2k::AnswerWizardPtr AnswerWizard={ read=get_AnswerWizard }; // 0, Yes
  __property Office_2k::MsoFeatureInstall FeatureInstall={ read=get_FeatureInstall }; // 0, No
  /*CoClassWriteProperties*/
  /*CoClassWriteEventDecls*/
private:
  TOutlookApplicationItemSend    FOnItemSend;
  TNotifyEvent                   FOnNewMail;
  TOutlookApplicationReminder    FOnReminder;
  TOutlookApplicationOptionsPagesAdd FOnOptionsPagesAdd;
  TNotifyEvent                   FOnStartup;
  TNotifyEvent                   FOnQuit;
__published:
  __property TOutlookApplicationItemSend OnItemSend={ read=FOnItemSend, write=FOnItemSend };
  __property TNotifyEvent OnNewMail={ read=FOnNewMail, write=FOnNewMail };
  __property TOutlookApplicationReminder OnReminder={ read=FOnReminder, write=FOnReminder };
  __property TOutlookApplicationOptionsPagesAdd OnOptionsPagesAdd={ read=FOnOptionsPagesAdd, write=FOnOptionsPagesAdd };
  __property TNotifyEvent OnStartup={ read=FOnStartup, write=FOnStartup };
  __property TNotifyEvent OnQuit={ read=FOnQuit, write=FOnQuit };
private:
  bool     FAutoQuit;
__published:
  __property bool AutoQuit = {read=FAutoQuit, write=FAutoQuit};
};

};     // namespace Outlook_2k

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Outlook_2k;
#endif

#pragma option pop

#endif // Outlook_2k_srvrH
