// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.0.1.1  $
// File generated on 1/24/2000 09:45:44 AM from Type Library described below.

// ************************************************************************ //
// Type Lib: d:\tlbgen\rampage\typelib\TypeLibraries\MSOUTL9.olb (1)
// IID\LCID: {00062FFF-0000-0000-C000-000000000046}\0
// Helpfile: d:\tlbgen\rampage\typelib\TypeLibraries\VBAOUTL9.CHM
// DepndLst: 
//   (1) v2.0 stdole, (D:\WINNT\System32\stdole2.tlb)
//   (2) v2.1 Office, (D:\msof2k\Office\mso9.dll)
//   (3) v4.0 StdVCL, (D:\tlbgen\rampage\typelib\typelibraries\testing\stdvcl40.tlb)
// ************************************************************************ //
#ifndef   __Outlook_2K_SRVR_h__
#define   __Outlook_2K_SRVR_h__

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0500)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "Office_2K.h"

#include "Outlook_2K.h"
namespace Outlook_2k
{

// *********************************************************************//
// HelpString: Microsoft Outlook 9.0 Object Library
// Version:    9.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOutlookApplication
// Help String      : 
// Default Interface: _Application
// Def. Intf. Object: _ApplicationPtr
// Def. Intf. DISP? : No
// Event   Interface: ApplicationEvents
// TypeFlags        : (11) AppObject CanCreate Predeclid
// *********************************************************************//
typedef void __fastcall (__closure * TOutlookApplicationItemSend)(System::TObject * Sender, 
                                                                  LPDISPATCH Item/*[in]*/, 
                                                                  TOLEBOOL* Cancel/*[in]*/);
typedef void __fastcall (__closure * TOutlookApplicationReminder)(System::TObject * Sender, 
                                                                  LPDISPATCH Item/*[in]*/);
typedef void __fastcall (__closure * TOutlookApplicationOptionsPagesAdd)(System::TObject * Sender, 
                                                                         Outlook_2k::PropertyPagesPtr Pages/*[in]*/);

class PACKAGE TOutlookApplication : public Oleserver::TOleServer
{
  _ApplicationPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOutlookApplication(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  _ApplicationPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ApplicationPtr intf);

  virtual void __fastcall InvokeEvent(int DispID, TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
  Outlook_2k::_ApplicationPtr __fastcall Get_Application(void)
  {
    return GetDefaultInterface()->get_Application();
  }

  Outlook_2k::OlObjectClass __fastcall Get_Class(void)
  {
    return GetDefaultInterface()->get_Class();
  }

  Outlook_2k::_NameSpacePtr __fastcall Get_Session(void)
  {
    return GetDefaultInterface()->get_Session();
  }

  LPDISPATCH __fastcall Get_Parent(void)
  {
    return GetDefaultInterface()->get_Parent();
  }

  Office_2k::AssistantPtr __fastcall Get_Assistant(void)
  {
    return GetDefaultInterface()->get_Assistant();
  }

  BSTR __fastcall Get_Name(void)
  {
    return GetDefaultInterface()->get_Name();
  }

  BSTR __fastcall Get_Version(void)
  {
    return GetDefaultInterface()->get_Version();
  }

  Office_2k::COMAddInsPtr __fastcall Get_COMAddIns(void)
  {
    return GetDefaultInterface()->get_COMAddIns();
  }

  Outlook_2k::_ExplorersPtr __fastcall Get_Explorers(void)
  {
    return GetDefaultInterface()->get_Explorers();
  }

  Outlook_2k::_InspectorsPtr __fastcall Get_Inspectors(void)
  {
    return GetDefaultInterface()->get_Inspectors();
  }

  Office_2k::LanguageSettingsPtr __fastcall Get_LanguageSettings(void)
  {
    return GetDefaultInterface()->get_LanguageSettings();
  }

  BSTR __fastcall Get_ProductCode(void)
  {
    return GetDefaultInterface()->get_ProductCode();
  }

  Office_2k::AnswerWizardPtr __fastcall Get_AnswerWizard(void)
  {
    return GetDefaultInterface()->get_AnswerWizard();
  }

  Office_2k::MsoFeatureInstall __fastcall Get_FeatureInstall(void)
  {
    return GetDefaultInterface()->get_FeatureInstall();
  }

  void __fastcall Set_FeatureInstall(Office_2k::MsoFeatureInstall FeatureInstall/*[in]*/)
  {
    GetDefaultInterface()->set_FeatureInstall(FeatureInstall/*[in]*/);
  }

  /*CoClassWriteMethods*/
  Outlook_2k::_ExplorerPtr __fastcall ActiveExplorer(void)
  {
    return GetDefaultInterface()->ActiveExplorer();
  }

  Outlook_2k::_InspectorPtr __fastcall ActiveInspector(void)
  {
    return GetDefaultInterface()->ActiveInspector();
  }

  LPDISPATCH __fastcall CreateItem(Outlook_2k::OlItemType ItemType/*[in]*/)
  {
    return GetDefaultInterface()->CreateItem(ItemType/*[in]*/);
  }

  LPDISPATCH __fastcall CreateItemFromTemplate(BSTR TemplatePath/*[in]*/, 
                                               TVariantInParam InFolder/*[in,opt]*/)
  {
    return GetDefaultInterface()->CreateItemFromTemplate(TemplatePath/*[in]*/, InFolder/*[in,opt]*/);
  }

  LPDISPATCH __fastcall CreateObject(BSTR ObjectName/*[in]*/)
  {
    return GetDefaultInterface()->CreateObject(ObjectName/*[in]*/);
  }

  Outlook_2k::_NameSpacePtr __fastcall GetNamespace(BSTR Type/*[in]*/)
  {
    return GetDefaultInterface()->GetNamespace(Type/*[in]*/);
  }

  void __fastcall Quit(void)
  {
    GetDefaultInterface()->Quit();
  }

  LPDISPATCH __fastcall ActiveWindow(void)
  {
    return GetDefaultInterface()->ActiveWindow();
  }

  /*CoClassWriteProperties*/
  __property Outlook_2k::_ApplicationPtr Application={ read=Get_Application }; // 0, Yes
  __property Outlook_2k::OlObjectClass Class={ read=Get_Class }; // 0, No
  __property Outlook_2k::_NameSpacePtr Session={ read=Get_Session }; // 0, Yes
  __property LPDISPATCH Parent={ read=Get_Parent }; // 0, No
  __property Office_2k::AssistantPtr Assistant={ read=Get_Assistant }; // 0, Yes
  __property BSTR Name={ read=Get_Name }; // 0, No
  __property BSTR Version={ read=Get_Version }; // 0, No
  __property Office_2k::COMAddInsPtr COMAddIns={ read=Get_COMAddIns }; // 0, Yes
  __property Outlook_2k::_ExplorersPtr Explorers={ read=Get_Explorers }; // 0, Yes
  __property Outlook_2k::_InspectorsPtr Inspectors={ read=Get_Inspectors }; // 0, Yes
  __property Office_2k::LanguageSettingsPtr LanguageSettings={ read=Get_LanguageSettings }; // 0, Yes
  __property BSTR ProductCode={ read=Get_ProductCode }; // 0, No
  __property Office_2k::AnswerWizardPtr AnswerWizard={ read=Get_AnswerWizard }; // 0, Yes
  __property Office_2k::MsoFeatureInstall FeatureInstall={ read=Get_FeatureInstall, write=Set_FeatureInstall }; // 0, No
  /*CoClassWriteProperties*/
  /*CoClassWriteEventDecls*/
private:
  TOutlookApplicationItemSend    FOnItemSend;
  TNotifyEvent                   FOnNewMail;
  TOutlookApplicationReminder    FOnReminder;
  TOutlookApplicationOptionsPagesAdd FOnOptionsPagesAdd;
  TNotifyEvent                   FOnStartup;
  TNotifyEvent                   FOnQuit;
__published:
  __property TOutlookApplicationItemSend OnItemSend={ read=FOnItemSend, write=FOnItemSend };
  __property TNotifyEvent OnNewMail={ read=FOnNewMail, write=FOnNewMail };
  __property TOutlookApplicationReminder OnReminder={ read=FOnReminder, write=FOnReminder };
  __property TOutlookApplicationOptionsPagesAdd OnOptionsPagesAdd={ read=FOnOptionsPagesAdd, write=FOnOptionsPagesAdd };
  __property TNotifyEvent OnStartup={ read=FOnStartup, write=FOnStartup };
  __property TNotifyEvent OnQuit={ read=FOnQuit, write=FOnQuit };
private:
  bool     FAutoQuit;
__published:
  __property bool AutoQuit = {read=FAutoQuit, write=FAutoQuit};
};

};     // namespace Outlook_2k

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Outlook_2k;
#endif

#pragma option pop

#endif // __Outlook_2K_SRVR_h__
