// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.0.1.1  $
// File generated on 1/24/2000 09:46:20 AM from Type Library described below.

// ************************************************************************ //
// Type Lib: d:\tlbgen\rampage\typelib\TypeLibraries\MSPPT9.olb (1)
// IID\LCID: {91493440-5A91-11CF-8700-00AA0060263B}\0
// Helpfile: d:\tlbgen\rampage\typelib\TypeLibraries\VBAPPT9.CHM
// DepndLst: 
//   (1) v2.0 stdole, (D:\WINNT\System32\stdole2.tlb)
//   (2) v2.1 Office, (D:\msof2k\Office\mso9.dll)
//   (3) v5.3 VBIDE, (D:\Program Files\Common Files\Microsoft Shared\VBA\VBA6\VBE6EXT.OLB)
//   (4) v4.0 StdVCL, (D:\tlbgen\rampage\typelib\typelibraries\testing\stdvcl40.tlb)
// ************************************************************************ //
#ifndef   __PowerPoint_2K_SRVR_h__
#define   __PowerPoint_2K_SRVR_h__

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0500)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "Office_2K.h"
#include "VBIDE_2K.h"

#include "PowerPoint_2K.h"
namespace Powerpoint_2k
{

// *********************************************************************//
// HelpString: Microsoft PowerPoint 9.0 Object Library
// Version:    2.6
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TPowerPointGlobal
// Help String      : 
// Default Interface: _Global
// Def. Intf. Object: _GlobalPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (27) AppObject CanCreate Predeclid Hidden
// *********************************************************************//
class PACKAGE TPowerPointGlobal : public Oleserver::TOleServer
{
  _GlobalPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TPowerPointGlobal(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  _GlobalPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_GlobalPtr intf);


  /*CoClassWriteArrayPropMethods*/
  Powerpoint_2k::PowerPointPresentationPtr __fastcall Get_ActivePresentation(void)
  {
    return GetDefaultInterface()->get_ActivePresentation();
  }

  Powerpoint_2k::DocumentWindowPtr __fastcall Get_ActiveWindow(void)
  {
    return GetDefaultInterface()->get_ActiveWindow();
  }

  Powerpoint_2k::AddInsPtr __fastcall Get_AddIns(void)
  {
    return GetDefaultInterface()->get_AddIns();
  }

  Powerpoint_2k::PowerPointApplicationPtr __fastcall Get_Application(void)
  {
    return GetDefaultInterface()->get_Application();
  }

  Office_2k::AssistantPtr __fastcall Get_Assistant(void)
  {
    return GetDefaultInterface()->get_Assistant();
  }

  Powerpoint_2k::PPDialogsPtr __fastcall Get_Dialogs(void)
  {
    return GetDefaultInterface()->get_Dialogs();
  }

  Powerpoint_2k::PresentationsPtr __fastcall Get_Presentations(void)
  {
    return GetDefaultInterface()->get_Presentations();
  }

  Powerpoint_2k::SlideShowWindowsPtr __fastcall Get_SlideShowWindows(void)
  {
    return GetDefaultInterface()->get_SlideShowWindows();
  }

  Powerpoint_2k::DocumentWindowsPtr __fastcall Get_Windoz(void)
  {
    return GetDefaultInterface()->get_Windoz();
  }

  Office_2k::CommandBarsPtr __fastcall Get_CommandBars(void)
  {
    return GetDefaultInterface()->get_CommandBars();
  }

  Office_2k::AnswerWizardPtr __fastcall Get_AnswerWizard(void)
  {
    return GetDefaultInterface()->get_AnswerWizard();
  }

  /*CoClassWriteMethods*/
  /*CoClassWriteProperties*/
  __property Powerpoint_2k::PowerPointPresentationPtr ActivePresentation={ read=Get_ActivePresentation }; // 0, Yes
  __property Powerpoint_2k::DocumentWindowPtr ActiveWindow={ read=Get_ActiveWindow }; // 0, Yes
  __property Powerpoint_2k::AddInsPtr AddIns={ read=Get_AddIns }; // 0, Yes
  __property Powerpoint_2k::PowerPointApplicationPtr Application={ read=Get_Application }; // 0, Yes
  __property Office_2k::AssistantPtr Assistant={ read=Get_Assistant }; // 0, Yes
  __property Powerpoint_2k::PPDialogsPtr Dialogs={ read=Get_Dialogs }; // 0, Yes
  __property Powerpoint_2k::PresentationsPtr Presentations={ read=Get_Presentations }; // 0, Yes
  __property Powerpoint_2k::SlideShowWindowsPtr SlideShowWindows={ read=Get_SlideShowWindows }; // 0, Yes
  __property Powerpoint_2k::DocumentWindowsPtr Windoz={ read=Get_Windoz }; // 0, Yes
  __property Office_2k::CommandBarsPtr CommandBars={ read=Get_CommandBars }; // 0, Yes
  __property Office_2k::AnswerWizardPtr AnswerWizard={ read=Get_AnswerWizard }; // 0, Yes
  /*CoClassWriteProperties*/
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TPowerPointSlide
// Help String      : 
// Default Interface: _Slide
// Def. Intf. Object: _SlidePtr
// Def. Intf. DISP? : No
// Event   Interface: SldEvents
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TPowerPointSlide : public Oleserver::TOleServer
{
  _SlidePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TPowerPointSlide(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  _SlidePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_SlidePtr intf);

  virtual void __fastcall InvokeEvent(int DispID, TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
  Powerpoint_2k::PowerPointApplicationPtr __fastcall Get_Application(void)
  {
    return GetDefaultInterface()->get_Application();
  }

  LPDISPATCH __fastcall Get_Parent(void)
  {
    return GetDefaultInterface()->get_Parent();
  }

  Powerpoint_2k::ShapesPtr __fastcall Get_Shapes(void)
  {
    return GetDefaultInterface()->get_Shapes();
  }

  Powerpoint_2k::HeadersFootersPtr __fastcall Get_HeadersFooters(void)
  {
    return GetDefaultInterface()->get_HeadersFooters();
  }

  Powerpoint_2k::SlideShowTransitionPtr __fastcall Get_SlideShowTransition(void)
  {
    return GetDefaultInterface()->get_SlideShowTransition();
  }

  Powerpoint_2k::ColorSchemePtr __fastcall Get_ColorScheme(void)
  {
    return GetDefaultInterface()->get_ColorScheme();
  }

  void __fastcall Set_ColorScheme(Powerpoint_2k::ColorSchemePtr ColorScheme/*[in]*/)
  {
    GetDefaultInterface()->set_ColorScheme(ColorScheme/*[in]*/);
  }

  Powerpoint_2k::ShapeRangePtr __fastcall Get_Background(void)
  {
    return GetDefaultInterface()->get_Background();
  }

  BSTR __fastcall Get_Name(void)
  {
    return GetDefaultInterface()->get_Name();
  }

  void __fastcall Set_Name(BSTR Name/*[in]*/)
  {
    GetDefaultInterface()->set_Name(Name/*[in]*/);
  }

  long __fastcall Get_SlideID(void)
  {
    return GetDefaultInterface()->get_SlideID();
  }

  int __fastcall Get_PrintSteps(void)
  {
    return GetDefaultInterface()->get_PrintSteps();
  }

  Powerpoint_2k::PpSlideLayout __fastcall Get_Layout(void)
  {
    return GetDefaultInterface()->get_Layout();
  }

  void __fastcall Set_Layout(Powerpoint_2k::PpSlideLayout Layout/*[in]*/)
  {
    GetDefaultInterface()->set_Layout(Layout/*[in]*/);
  }

  Powerpoint_2k::TagsPtr __fastcall Get_Tags(void)
  {
    return GetDefaultInterface()->get_Tags();
  }

  int __fastcall Get_SlideIndex(void)
  {
    return GetDefaultInterface()->get_SlideIndex();
  }

  int __fastcall Get_SlideNumber(void)
  {
    return GetDefaultInterface()->get_SlideNumber();
  }

  Office_2k::MsoTriState __fastcall Get_DisplayMasterShapes(void)
  {
    return GetDefaultInterface()->get_DisplayMasterShapes();
  }

  void __fastcall Set_DisplayMasterShapes(Office_2k::MsoTriState DisplayMasterShapes/*[in]*/)
  {
    GetDefaultInterface()->set_DisplayMasterShapes(DisplayMasterShapes/*[in]*/);
  }

  Office_2k::MsoTriState __fastcall Get_FollowMasterBackground(void)
  {
    return GetDefaultInterface()->get_FollowMasterBackground();
  }

  void __fastcall Set_FollowMasterBackground(Office_2k::MsoTriState FollowMasterBackground/*[in]*/)
  {
    GetDefaultInterface()->set_FollowMasterBackground(FollowMasterBackground/*[in]*/);
  }

  Powerpoint_2k::SlideRangePtr __fastcall Get_NotesPage(void)
  {
    return GetDefaultInterface()->get_NotesPage();
  }

  Powerpoint_2k::_MasterPtr __fastcall Get_Master(void)
  {
    return GetDefaultInterface()->get_Master();
  }

  Powerpoint_2k::HyperlinksPtr __fastcall Get_Hyperlinks(void)
  {
    return GetDefaultInterface()->get_Hyperlinks();
  }

  Office_2k::ScriptsPtr __fastcall Get_Scripts(void)
  {
    return GetDefaultInterface()->get_Scripts();
  }

  /*CoClassWriteMethods*/
  void __fastcall Select(void)
  {
    GetDefaultInterface()->Select();
  }

  void __fastcall Cut(void)
  {
    GetDefaultInterface()->Cut();
  }

  void __fastcall Copy(void)
  {
    GetDefaultInterface()->Copy();
  }

  Powerpoint_2k::SlideRangePtr __fastcall Duplicate(void)
  {
    return GetDefaultInterface()->Duplicate();
  }

  void __fastcall Delete(void)
  {
    GetDefaultInterface()->Delete();
  }

  void __fastcall Export(BSTR FileName/*[in]*/, BSTR FilterName/*[in]*/, 
                         int ScaleWidth/*[in,def,opt]*/, int ScaleHeight/*[in,def,opt]*/)
  {
    GetDefaultInterface()->Export(FileName/*[in]*/, FilterName/*[in]*/, ScaleWidth/*[in,def,opt]*/, 
                                  ScaleHeight/*[in,def,opt]*/);
  }

  /*CoClassWriteProperties*/
  __property Powerpoint_2k::PowerPointApplicationPtr Application={ read=Get_Application }; // 0, Yes
  __property LPDISPATCH Parent={ read=Get_Parent }; // 0, No
  __property Powerpoint_2k::ShapesPtr Shapes={ read=Get_Shapes }; // 0, Yes
  __property Powerpoint_2k::HeadersFootersPtr HeadersFooters={ read=Get_HeadersFooters }; // 0, Yes
  __property Powerpoint_2k::SlideShowTransitionPtr SlideShowTransition={ read=Get_SlideShowTransition }; // 0, Yes
  __property Powerpoint_2k::ShapeRangePtr Background={ read=Get_Background }; // 0, Yes
  __property long SlideID={ read=Get_SlideID }; // 0, No
  __property int PrintSteps={ read=Get_PrintSteps }; // 0, No
  __property Powerpoint_2k::TagsPtr Tags={ read=Get_Tags }; // 0, Yes
  __property int SlideIndex={ read=Get_SlideIndex }; // 0, No
  __property int SlideNumber={ read=Get_SlideNumber }; // 0, No
  __property Powerpoint_2k::SlideRangePtr NotesPage={ read=Get_NotesPage }; // 0, Yes
  __property Powerpoint_2k::_MasterPtr Master={ read=Get_Master }; // 0, Yes
  __property Powerpoint_2k::HyperlinksPtr Hyperlinks={ read=Get_Hyperlinks }; // 0, Yes
  __property Office_2k::ScriptsPtr Scripts={ read=Get_Scripts }; // 0, Yes
  /*CoClassWriteProperties*/
  __property Powerpoint_2k::ColorSchemePtr ColorScheme={ read=Get_ColorScheme, write=Set_ColorScheme, stored=false }; // 0, Yes
  __property BSTR Name={ read=Get_Name, write=Set_Name, stored=false }; // 0, No
  __property Powerpoint_2k::PpSlideLayout Layout={ read=Get_Layout, write=Set_Layout, stored=false }; // 0, No
  __property Office_2k::MsoTriState DisplayMasterShapes={ read=Get_DisplayMasterShapes, write=Set_DisplayMasterShapes, stored=false }; // 0, No
  __property Office_2k::MsoTriState FollowMasterBackground={ read=Get_FollowMasterBackground, write=Set_FollowMasterBackground, stored=false }; // 0, No
  /*CoClassWriteEventDecls*/
private:
__published:
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TPowerPointPresentation
// Help String      : 
// Default Interface: _Presentation
// Def. Intf. Object: _PresentationPtr
// Def. Intf. DISP? : No
// Event   Interface: PresEvents
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TPowerPointPresentation : public Oleserver::TOleServer
{
  _PresentationPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TPowerPointPresentation(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  _PresentationPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_PresentationPtr intf);

  virtual void __fastcall InvokeEvent(int DispID, TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
  Powerpoint_2k::PowerPointApplicationPtr __fastcall Get_Application(void)
  {
    return GetDefaultInterface()->get_Application();
  }

  LPDISPATCH __fastcall Get_Parent(void)
  {
    return GetDefaultInterface()->get_Parent();
  }

  Powerpoint_2k::_MasterPtr __fastcall Get_SlideMaster(void)
  {
    return GetDefaultInterface()->get_SlideMaster();
  }

  Powerpoint_2k::_MasterPtr __fastcall Get_TitleMaster(void)
  {
    return GetDefaultInterface()->get_TitleMaster();
  }

  Office_2k::MsoTriState __fastcall Get_HasTitleMaster(void)
  {
    return GetDefaultInterface()->get_HasTitleMaster();
  }

  BSTR __fastcall Get_TemplateName(void)
  {
    return GetDefaultInterface()->get_TemplateName();
  }

  Powerpoint_2k::_MasterPtr __fastcall Get_NotesMaster(void)
  {
    return GetDefaultInterface()->get_NotesMaster();
  }

  Powerpoint_2k::_MasterPtr __fastcall Get_HandoutMaster(void)
  {
    return GetDefaultInterface()->get_HandoutMaster();
  }

  Powerpoint_2k::SlidesPtr __fastcall Get_Slides(void)
  {
    return GetDefaultInterface()->get_Slides();
  }

  Powerpoint_2k::PageSetupPtr __fastcall Get_PageSetup(void)
  {
    return GetDefaultInterface()->get_PageSetup();
  }

  Powerpoint_2k::ColorSchemesPtr __fastcall Get_ColorSchemes(void)
  {
    return GetDefaultInterface()->get_ColorSchemes();
  }

  Powerpoint_2k::ExtraColorsPtr __fastcall Get_ExtraColors(void)
  {
    return GetDefaultInterface()->get_ExtraColors();
  }

  Powerpoint_2k::SlideShowSettingsPtr __fastcall Get_SlideShowSettings(void)
  {
    return GetDefaultInterface()->get_SlideShowSettings();
  }

  Powerpoint_2k::FontsPtr __fastcall Get_Fonts(void)
  {
    return GetDefaultInterface()->get_Fonts();
  }

  Powerpoint_2k::DocumentWindowsPtr __fastcall Get_Windoz(void)
  {
    return GetDefaultInterface()->get_Windoz();
  }

  Powerpoint_2k::TagsPtr __fastcall Get_Tags(void)
  {
    return GetDefaultInterface()->get_Tags();
  }

  Powerpoint_2k::ShapePtr __fastcall Get_DefaultShape(void)
  {
    return GetDefaultInterface()->get_DefaultShape();
  }

  LPDISPATCH __fastcall Get_BuiltInDocumentProperties(void)
  {
    return GetDefaultInterface()->get_BuiltInDocumentProperties();
  }

  LPDISPATCH __fastcall Get_CustomDocumentProperties(void)
  {
    return GetDefaultInterface()->get_CustomDocumentProperties();
  }

  Vbide_2k::VBProjectPtr __fastcall Get_VBProject(void)
  {
    return GetDefaultInterface()->get_VBProject();
  }

  Office_2k::MsoTriState __fastcall Get_ReadOnly(void)
  {
    return GetDefaultInterface()->get_ReadOnly();
  }

  BSTR __fastcall Get_FullName(void)
  {
    return GetDefaultInterface()->get_FullName();
  }

  BSTR __fastcall Get_Name(void)
  {
    return GetDefaultInterface()->get_Name();
  }

  BSTR __fastcall Get_Path(void)
  {
    return GetDefaultInterface()->get_Path();
  }

  Office_2k::MsoTriState __fastcall Get_Saved(void)
  {
    return GetDefaultInterface()->get_Saved();
  }

  void __fastcall Set_Saved(Office_2k::MsoTriState Saved/*[in]*/)
  {
    GetDefaultInterface()->set_Saved(Saved/*[in]*/);
  }

  Powerpoint_2k::PpDirection __fastcall Get_LayoutDirection(void)
  {
    return GetDefaultInterface()->get_LayoutDirection();
  }

  void __fastcall Set_LayoutDirection(Powerpoint_2k::PpDirection LayoutDirection/*[in]*/)
  {
    GetDefaultInterface()->set_LayoutDirection(LayoutDirection/*[in]*/);
  }

  Powerpoint_2k::PrintOptionsPtr __fastcall Get_PrintOptions(void)
  {
    return GetDefaultInterface()->get_PrintOptions();
  }

  LPDISPATCH __fastcall Get_Container(void)
  {
    return GetDefaultInterface()->get_Container();
  }

  Office_2k::MsoTriState __fastcall Get_DisplayComments(void)
  {
    return GetDefaultInterface()->get_DisplayComments();
  }

  void __fastcall Set_DisplayComments(Office_2k::MsoTriState DisplayComments/*[in]*/)
  {
    GetDefaultInterface()->set_DisplayComments(DisplayComments/*[in]*/);
  }

  Powerpoint_2k::PpFarEastLineBreakLevel __fastcall Get_FarEastLineBreakLevel(void)
  {
    return GetDefaultInterface()->get_FarEastLineBreakLevel();
  }

  void __fastcall Set_FarEastLineBreakLevel(Powerpoint_2k::PpFarEastLineBreakLevel FarEastLineBreakLevel/*[in]*/)
  {
    GetDefaultInterface()->set_FarEastLineBreakLevel(FarEastLineBreakLevel/*[in]*/);
  }

  BSTR __fastcall Get_NoLineBreakBefore(void)
  {
    return GetDefaultInterface()->get_NoLineBreakBefore();
  }

  void __fastcall Set_NoLineBreakBefore(BSTR NoLineBreakBefore/*[in]*/)
  {
    GetDefaultInterface()->set_NoLineBreakBefore(NoLineBreakBefore/*[in]*/);
  }

  BSTR __fastcall Get_NoLineBreakAfter(void)
  {
    return GetDefaultInterface()->get_NoLineBreakAfter();
  }

  void __fastcall Set_NoLineBreakAfter(BSTR NoLineBreakAfter/*[in]*/)
  {
    GetDefaultInterface()->set_NoLineBreakAfter(NoLineBreakAfter/*[in]*/);
  }

  Powerpoint_2k::SlideShowWindowPtr __fastcall Get_SlideShowWindow(void)
  {
    return GetDefaultInterface()->get_SlideShowWindow();
  }

  Office_2k::MsoFarEastLineBreakLanguageID __fastcall Get_FarEastLineBreakLanguage(void)
  {
    return GetDefaultInterface()->get_FarEastLineBreakLanguage();
  }

  void __fastcall Set_FarEastLineBreakLanguage(Office_2k::MsoFarEastLineBreakLanguageID FarEastLineBreakLanguage/*[in]*/)
  {
    GetDefaultInterface()->set_FarEastLineBreakLanguage(FarEastLineBreakLanguage/*[in]*/);
  }

  Office_2k::MsoLanguageID __fastcall Get_DefaultLanguageID(void)
  {
    return GetDefaultInterface()->get_DefaultLanguageID();
  }

  void __fastcall Set_DefaultLanguageID(Office_2k::MsoLanguageID DefaultLanguageID/*[in]*/)
  {
    GetDefaultInterface()->set_DefaultLanguageID(DefaultLanguageID/*[in]*/);
  }

  Office_2k::CommandBarsPtr __fastcall Get_CommandBars(void)
  {
    return GetDefaultInterface()->get_CommandBars();
  }

  Powerpoint_2k::PublishObjectsPtr __fastcall Get_PublishObjects(void)
  {
    return GetDefaultInterface()->get_PublishObjects();
  }

  Powerpoint_2k::WebOptionsPtr __fastcall Get_WebOptions(void)
  {
    return GetDefaultInterface()->get_WebOptions();
  }

  Office_2k::HTMLProjectPtr __fastcall Get_HTMLProject(void)
  {
    return GetDefaultInterface()->get_HTMLProject();
  }

  Office_2k::MsoTriState __fastcall Get_EnvelopeVisible(void)
  {
    return GetDefaultInterface()->get_EnvelopeVisible();
  }

  void __fastcall Set_EnvelopeVisible(Office_2k::MsoTriState EnvelopeVisible/*[in]*/)
  {
    GetDefaultInterface()->set_EnvelopeVisible(EnvelopeVisible/*[in]*/);
  }

  Office_2k::MsoTriState __fastcall Get_VBASigned(void)
  {
    return GetDefaultInterface()->get_VBASigned();
  }

  /*CoClassWriteMethods*/
  Powerpoint_2k::_MasterPtr __fastcall AddTitleMaster(void)
  {
    return GetDefaultInterface()->AddTitleMaster();
  }

  void __fastcall ApplyTemplate(BSTR FileName/*[in]*/)
  {
    GetDefaultInterface()->ApplyTemplate(FileName/*[in]*/);
  }

  Powerpoint_2k::DocumentWindowPtr __fastcall NewWindow(void)
  {
    return GetDefaultInterface()->NewWindow();
  }

  void __fastcall FollowHyperlink(BSTR Address/*[in]*/, BSTR SubAddress/*[in,def,opt]*/, 
                                  TOLEBOOL NewWindow/*[in,def,opt]*/, 
                                  TOLEBOOL AddHistory/*[in,def,opt]*/, 
                                  BSTR ExtraInfo/*[in,def,opt]*/, 
                                  Office_2k::MsoExtraInfoMethod Method/*[in,def,opt]*/, 
                                  BSTR HeaderInfo/*[in,def,opt]*/)
  {
    GetDefaultInterface()->FollowHyperlink(Address/*[in]*/, SubAddress/*[in,def,opt]*/, 
                                           NewWindow/*[in,def,opt]*/, AddHistory/*[in,def,opt]*/, 
                                           ExtraInfo/*[in,def,opt]*/, Method/*[in,def,opt]*/, 
                                           HeaderInfo/*[in,def,opt]*/);
  }

  void __fastcall AddToFavorites(void)
  {
    GetDefaultInterface()->AddToFavorites();
  }

  void __fastcall PrintOut(int From/*[in,def,opt]*/, int To/*[in,def,opt]*/, 
                           BSTR PrintToFile/*[in,def,opt]*/, int Copies/*[in,def,opt]*/, 
                           Office_2k::MsoTriState Collate/*[in,def,opt]*/)
  {
    GetDefaultInterface()->PrintOut(From/*[in,def,opt]*/, To/*[in,def,opt]*/, 
                                    PrintToFile/*[in,def,opt]*/, Copies/*[in,def,opt]*/, 
                                    Collate/*[in,def,opt]*/);
  }

  void __fastcall Save(void)
  {
    GetDefaultInterface()->Save();
  }

  void __fastcall SaveAs(BSTR FileName/*[in]*/, 
                         Powerpoint_2k::PpSaveAsFileType FileFormat/*[in,def,opt]*/, 
                         Office_2k::MsoTriState EmbedTrueTypeFonts/*[in,def,opt]*/)
  {
    GetDefaultInterface()->SaveAs(FileName/*[in]*/, FileFormat/*[in,def,opt]*/, 
                                  EmbedTrueTypeFonts/*[in,def,opt]*/);
  }

  void __fastcall SaveCopyAs(BSTR FileName/*[in]*/, 
                             Powerpoint_2k::PpSaveAsFileType FileFormat/*[in,def,opt]*/, 
                             Office_2k::MsoTriState EmbedTrueTypeFonts/*[in,def,opt]*/)
  {
    GetDefaultInterface()->SaveCopyAs(FileName/*[in]*/, FileFormat/*[in,def,opt]*/, 
                                      EmbedTrueTypeFonts/*[in,def,opt]*/);
  }

  void __fastcall Export(BSTR Path/*[in]*/, BSTR FilterName/*[in]*/, int ScaleWidth/*[in,def,opt]*/, 
                         int ScaleHeight/*[in,def,opt]*/)
  {
    GetDefaultInterface()->Export(Path/*[in]*/, FilterName/*[in]*/, ScaleWidth/*[in,def,opt]*/, 
                                  ScaleHeight/*[in,def,opt]*/);
  }

  void __fastcall Close(void)
  {
    GetDefaultInterface()->Close();
  }

  void __fastcall SetUndoText(BSTR Text/*[in]*/)
  {
    GetDefaultInterface()->SetUndoText(Text/*[in]*/);
  }

  void __fastcall UpdateLinks(void)
  {
    GetDefaultInterface()->UpdateLinks();
  }

  void __fastcall WebPagePreview(void)
  {
    GetDefaultInterface()->WebPagePreview();
  }

  void __fastcall ReloadAs(Office_2k::MsoEncoding cp/*[in]*/)
  {
    GetDefaultInterface()->ReloadAs(cp/*[in]*/);
  }

  void __fastcall MakeIntoTemplate(Office_2k::MsoTriState IsDesignTemplate/*[in]*/)
  {
    GetDefaultInterface()->MakeIntoTemplate(IsDesignTemplate/*[in]*/);
  }

  void __fastcall sblt(BSTR s/*[in]*/)
  {
    GetDefaultInterface()->sblt(s/*[in]*/);
  }

  /*CoClassWriteProperties*/
  __property Powerpoint_2k::PowerPointApplicationPtr Application={ read=Get_Application }; // 0, Yes
  __property LPDISPATCH Parent={ read=Get_Parent }; // 0, No
  __property Powerpoint_2k::_MasterPtr SlideMaster={ read=Get_SlideMaster }; // 0, Yes
  __property Powerpoint_2k::_MasterPtr TitleMaster={ read=Get_TitleMaster }; // 0, Yes
  __property Office_2k::MsoTriState HasTitleMaster={ read=Get_HasTitleMaster }; // 0, No
  __property BSTR TemplateName={ read=Get_TemplateName }; // 0, No
  __property Powerpoint_2k::_MasterPtr NotesMaster={ read=Get_NotesMaster }; // 0, Yes
  __property Powerpoint_2k::_MasterPtr HandoutMaster={ read=Get_HandoutMaster }; // 0, Yes
  __property Powerpoint_2k::SlidesPtr Slides={ read=Get_Slides }; // 0, Yes
  __property Powerpoint_2k::PageSetupPtr PageSetup={ read=Get_PageSetup }; // 0, Yes
  __property Powerpoint_2k::ColorSchemesPtr ColorSchemes={ read=Get_ColorSchemes }; // 0, Yes
  __property Powerpoint_2k::ExtraColorsPtr ExtraColors={ read=Get_ExtraColors }; // 0, Yes
  __property Powerpoint_2k::SlideShowSettingsPtr SlideShowSettings={ read=Get_SlideShowSettings }; // 0, Yes
  __property Powerpoint_2k::FontsPtr Fonts={ read=Get_Fonts }; // 0, Yes
  __property Powerpoint_2k::DocumentWindowsPtr Windoz={ read=Get_Windoz }; // 0, Yes
  __property Powerpoint_2k::TagsPtr Tags={ read=Get_Tags }; // 0, Yes
  __property Powerpoint_2k::ShapePtr DefaultShape={ read=Get_DefaultShape }; // 0, Yes
  __property LPDISPATCH BuiltInDocumentProperties={ read=Get_BuiltInDocumentProperties }; // 0, No
  __property LPDISPATCH CustomDocumentProperties={ read=Get_CustomDocumentProperties }; // 0, No
  __property Vbide_2k::VBProjectPtr VBProject={ read=Get_VBProject }; // 0, Yes
  __property Office_2k::MsoTriState ReadOnly={ read=Get_ReadOnly }; // 0, No
  __property BSTR FullName={ read=Get_FullName }; // 0, No
  __property BSTR Name={ read=Get_Name }; // 0, No
  __property BSTR Path={ read=Get_Path }; // 0, No
  __property Powerpoint_2k::PrintOptionsPtr PrintOptions={ read=Get_PrintOptions }; // 0, Yes
  __property LPDISPATCH Container={ read=Get_Container }; // 0, No
  __property Powerpoint_2k::SlideShowWindowPtr SlideShowWindow={ read=Get_SlideShowWindow }; // 0, Yes
  __property Office_2k::CommandBarsPtr CommandBars={ read=Get_CommandBars }; // 0, Yes
  __property Powerpoint_2k::PublishObjectsPtr PublishObjects={ read=Get_PublishObjects }; // 0, Yes
  __property Powerpoint_2k::WebOptionsPtr WebOptions={ read=Get_WebOptions }; // 0, Yes
  __property Office_2k::HTMLProjectPtr HTMLProject={ read=Get_HTMLProject }; // 0, Yes
  __property Office_2k::MsoTriState VBASigned={ read=Get_VBASigned }; // 0, No
  /*CoClassWriteProperties*/
  __property Office_2k::MsoTriState Saved={ read=Get_Saved, write=Set_Saved, stored=false }; // 0, No
  __property Powerpoint_2k::PpDirection LayoutDirection={ read=Get_LayoutDirection, write=Set_LayoutDirection, stored=false }; // 0, No
  __property Office_2k::MsoTriState DisplayComments={ read=Get_DisplayComments, write=Set_DisplayComments, stored=false }; // 0, No
  __property Powerpoint_2k::PpFarEastLineBreakLevel FarEastLineBreakLevel={ read=Get_FarEastLineBreakLevel, write=Set_FarEastLineBreakLevel, stored=false }; // 0, No
  __property BSTR NoLineBreakBefore={ read=Get_NoLineBreakBefore, write=Set_NoLineBreakBefore, stored=false }; // 0, No
  __property BSTR NoLineBreakAfter={ read=Get_NoLineBreakAfter, write=Set_NoLineBreakAfter, stored=false }; // 0, No
  __property Office_2k::MsoFarEastLineBreakLanguageID FarEastLineBreakLanguage={ read=Get_FarEastLineBreakLanguage, write=Set_FarEastLineBreakLanguage, stored=false }; // 0, No
  __property Office_2k::MsoLanguageID DefaultLanguageID={ read=Get_DefaultLanguageID, write=Set_DefaultLanguageID, stored=false }; // 0, No
  __property Office_2k::MsoTriState EnvelopeVisible={ read=Get_EnvelopeVisible, write=Set_EnvelopeVisible, stored=false }; // 0, No
  /*CoClassWriteEventDecls*/
private:
__published:
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TPowerPointApplication
// Help String      : 
// Default Interface: _Application
// Def. Intf. Object: _ApplicationPtr
// Def. Intf. DISP? : No
// Event   Interface: EApplication
// TypeFlags        : (2) CanCreate
// *********************************************************************//
typedef void __fastcall (__closure * TPowerPointApplicationWindowSelectionChange)(System::TObject * Sender, 
                                                                                  Powerpoint_2k::SelectionPtr Sel/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationWindowBeforeRightClick)(System::TObject * Sender, 
                                                                                   Powerpoint_2k::SelectionPtr Sel/*[in]*/, 
                                                                                   TOLEBOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TPowerPointApplicationWindowBeforeDoubleClick)(System::TObject * Sender, 
                                                                                    Powerpoint_2k::SelectionPtr Sel/*[in]*/, 
                                                                                    TOLEBOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TPowerPointApplicationPresentationClose)(System::TObject * Sender, 
                                                                              Powerpoint_2k::PowerPointPresentationPtr Pres/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationPresentationSave)(System::TObject * Sender, 
                                                                             Powerpoint_2k::PowerPointPresentationPtr Pres/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationPresentationOpen)(System::TObject * Sender, 
                                                                             Powerpoint_2k::PowerPointPresentationPtr Pres/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationNewPresentation)(System::TObject * Sender, 
                                                                            Powerpoint_2k::PowerPointPresentationPtr Pres/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationPresentationNewSlide)(System::TObject * Sender, 
                                                                                 Powerpoint_2k::PowerPointSlidePtr Sld/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationWindowActivate)(System::TObject * Sender, 
                                                                           Powerpoint_2k::PowerPointPresentationPtr Pres/*[in]*/, 
                                                                           Powerpoint_2k::DocumentWindowPtr Wn/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationWindowDeactivate)(System::TObject * Sender, 
                                                                             Powerpoint_2k::PowerPointPresentationPtr Pres/*[in]*/, 
                                                                             Powerpoint_2k::DocumentWindowPtr Wn/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationSlideShowBegin)(System::TObject * Sender, 
                                                                           Powerpoint_2k::SlideShowWindowPtr Wn/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationSlideShowNextBuild)(System::TObject * Sender, 
                                                                               Powerpoint_2k::SlideShowWindowPtr Wn/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationSlideShowNextSlide)(System::TObject * Sender, 
                                                                               Powerpoint_2k::SlideShowWindowPtr Wn/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationSlideShowEnd)(System::TObject * Sender, 
                                                                         Powerpoint_2k::PowerPointPresentationPtr Pres/*[in]*/);
typedef void __fastcall (__closure * TPowerPointApplicationPresentationPrint)(System::TObject * Sender, 
                                                                              Powerpoint_2k::PowerPointPresentationPtr Pres/*[in]*/);

class PACKAGE TPowerPointApplication : public Oleserver::TOleServer
{
  _ApplicationPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TPowerPointApplication(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  _ApplicationPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_ApplicationPtr intf);

  virtual void __fastcall InvokeEvent(int DispID, TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
  Powerpoint_2k::PresentationsPtr __fastcall Get_Presentations(void)
  {
    return GetDefaultInterface()->get_Presentations();
  }

  Powerpoint_2k::DocumentWindowsPtr __fastcall Get_Windoz(void)
  {
    return GetDefaultInterface()->get_Windoz();
  }

  Powerpoint_2k::PPDialogsPtr __fastcall Get_Dialogs(void)
  {
    return GetDefaultInterface()->get_Dialogs();
  }

  Powerpoint_2k::DocumentWindowPtr __fastcall Get_ActiveWindow(void)
  {
    return GetDefaultInterface()->get_ActiveWindow();
  }

  Powerpoint_2k::PowerPointPresentationPtr __fastcall Get_ActivePresentation(void)
  {
    return GetDefaultInterface()->get_ActivePresentation();
  }

  Powerpoint_2k::SlideShowWindowsPtr __fastcall Get_SlideShowWindows(void)
  {
    return GetDefaultInterface()->get_SlideShowWindows();
  }

  Office_2k::CommandBarsPtr __fastcall Get_CommandBars(void)
  {
    return GetDefaultInterface()->get_CommandBars();
  }

  BSTR __fastcall Get_Path(void)
  {
    return GetDefaultInterface()->get_Path();
  }

  BSTR __fastcall Get_Name(void)
  {
    return GetDefaultInterface()->get_Name();
  }

  BSTR __fastcall Get_Caption(void)
  {
    return GetDefaultInterface()->get_Caption();
  }

  void __fastcall Set_Caption(BSTR Caption/*[in]*/)
  {
    GetDefaultInterface()->set_Caption(Caption/*[in]*/);
  }

  Office_2k::AssistantPtr __fastcall Get_Assistant(void)
  {
    return GetDefaultInterface()->get_Assistant();
  }

  Office_2k::FileSearchPtr __fastcall Get_FileSearch(void)
  {
    return GetDefaultInterface()->get_FileSearch();
  }

  Office_2k::IFindPtr __fastcall Get_FileFind(void)
  {
    return GetDefaultInterface()->get_FileFind();
  }

  BSTR __fastcall Get_Build(void)
  {
    return GetDefaultInterface()->get_Build();
  }

  BSTR __fastcall Get_Version(void)
  {
    return GetDefaultInterface()->get_Version();
  }

  BSTR __fastcall Get_OperatingSystem(void)
  {
    return GetDefaultInterface()->get_OperatingSystem();
  }

  BSTR __fastcall Get_ActivePrinter(void)
  {
    return GetDefaultInterface()->get_ActivePrinter();
  }

  long __fastcall Get_Creator(void)
  {
    return GetDefaultInterface()->get_Creator();
  }

  Powerpoint_2k::AddInsPtr __fastcall Get_AddIns(void)
  {
    return GetDefaultInterface()->get_AddIns();
  }

  Vbide_2k::VBEPtr __fastcall Get_VBE(void)
  {
    return GetDefaultInterface()->get_VBE();
  }

  float __fastcall Get_Left(void)
  {
    return GetDefaultInterface()->get_Left();
  }

  void __fastcall Set_Left(float Left/*[in]*/)
  {
    GetDefaultInterface()->set_Left(Left/*[in]*/);
  }

  float __fastcall Get_Top(void)
  {
    return GetDefaultInterface()->get_Top();
  }

  void __fastcall Set_Top(float Top/*[in]*/)
  {
    GetDefaultInterface()->set_Top(Top/*[in]*/);
  }

  float __fastcall Get_Width(void)
  {
    return GetDefaultInterface()->get_Width();
  }

  void __fastcall Set_Width(float Width/*[in]*/)
  {
    GetDefaultInterface()->set_Width(Width/*[in]*/);
  }

  float __fastcall Get_Height(void)
  {
    return GetDefaultInterface()->get_Height();
  }

  void __fastcall Set_Height(float Height/*[in]*/)
  {
    GetDefaultInterface()->set_Height(Height/*[in]*/);
  }

  Powerpoint_2k::PpWindowState __fastcall Get_WindowState(void)
  {
    return GetDefaultInterface()->get_WindowState();
  }

  void __fastcall Set_WindowState(Powerpoint_2k::PpWindowState WindowState/*[in]*/)
  {
    GetDefaultInterface()->set_WindowState(WindowState/*[in]*/);
  }

  Office_2k::MsoTriState __fastcall Get_Visible(void)
  {
    return GetDefaultInterface()->get_Visible();
  }

  void __fastcall Set_Visible(Office_2k::MsoTriState Visible/*[in]*/)
  {
    GetDefaultInterface()->set_Visible(Visible/*[in]*/);
  }

  Office_2k::MsoTriState __fastcall Get_Active(void)
  {
    return GetDefaultInterface()->get_Active();
  }

  Office_2k::AnswerWizardPtr __fastcall Get_AnswerWizard(void)
  {
    return GetDefaultInterface()->get_AnswerWizard();
  }

  Office_2k::COMAddInsPtr __fastcall Get_COMAddIns(void)
  {
    return GetDefaultInterface()->get_COMAddIns();
  }

  BSTR __fastcall Get_ProductCode(void)
  {
    return GetDefaultInterface()->get_ProductCode();
  }

  Powerpoint_2k::DefaultWebOptionsPtr __fastcall Get_DefaultWebOptions(void)
  {
    return GetDefaultInterface()->get_DefaultWebOptions();
  }

  Office_2k::LanguageSettingsPtr __fastcall Get_LanguageSettings(void)
  {
    return GetDefaultInterface()->get_LanguageSettings();
  }

  Office_2k::MsoDebugOptionsPtr __fastcall Get_MsoDebugOptions(void)
  {
    return GetDefaultInterface()->get_MsoDebugOptions();
  }

  Office_2k::MsoTriState __fastcall Get_ShowWindowsInTaskbar(void)
  {
    return GetDefaultInterface()->get_ShowWindowsInTaskbar();
  }

  void __fastcall Set_ShowWindowsInTaskbar(Office_2k::MsoTriState ShowWindowsInTaskbar/*[in]*/)
  {
    GetDefaultInterface()->set_ShowWindowsInTaskbar(ShowWindowsInTaskbar/*[in]*/);
  }

  Powerpoint_2k::MarkerPtr __fastcall Get_Marker(void)
  {
    return GetDefaultInterface()->get_Marker();
  }

  Office_2k::MsoFeatureInstall __fastcall Get_FeatureInstall(void)
  {
    return GetDefaultInterface()->get_FeatureInstall();
  }

  void __fastcall Set_FeatureInstall(Office_2k::MsoFeatureInstall FeatureInstall/*[in]*/)
  {
    GetDefaultInterface()->set_FeatureInstall(FeatureInstall/*[in]*/);
  }

  /*CoClassWriteMethods*/
  void __fastcall Help(BSTR HelpFile/*[in,def,opt]*/, int ContextID/*[in,def,opt]*/)
  {
    GetDefaultInterface()->Help(HelpFile/*[in,def,opt]*/, ContextID/*[in,def,opt]*/);
  }

  void __fastcall Quit(void)
  {
    GetDefaultInterface()->Quit();
  }

  TVariant __fastcall Run(BSTR MacroName/*[in]*/, LPSAFEARRAY* safeArrayOfParams/*[in]*/)
  {
    return GetDefaultInterface()->Run(MacroName/*[in]*/, safeArrayOfParams/*[in]*/);
  }

  Powerpoint_2k::FileDialogPtr __fastcall FileDialog(Powerpoint_2k::PpFileDialogType Type/*[in]*/)
  {
    return GetDefaultInterface()->FileDialog(Type/*[in]*/);
  }

  void __fastcall Activate(void)
  {
    GetDefaultInterface()->Activate();
  }

  TOLEBOOL __fastcall GetOptionFlag(long Option/*[in]*/, TOLEBOOL Persist/*[in,def,opt]*/)
  {
    return GetDefaultInterface()->GetOptionFlag(Option/*[in]*/, Persist/*[in,def,opt]*/);
  }

  void __fastcall SetOptionFlag(long Option/*[in]*/, TOLEBOOL State/*[in]*/, 
                                TOLEBOOL Persist/*[in,def,opt]*/)
  {
    GetDefaultInterface()->SetOptionFlag(Option/*[in]*/, State/*[in]*/, Persist/*[in,def,opt]*/);
  }

  /*CoClassWriteProperties*/
  __property Powerpoint_2k::PresentationsPtr Presentations={ read=Get_Presentations }; // 0, Yes
  __property Powerpoint_2k::DocumentWindowsPtr Windoz={ read=Get_Windoz }; // 0, Yes
  __property Powerpoint_2k::PPDialogsPtr Dialogs={ read=Get_Dialogs }; // 0, Yes
  __property Powerpoint_2k::DocumentWindowPtr ActiveWindow={ read=Get_ActiveWindow }; // 0, Yes
  __property Powerpoint_2k::PowerPointPresentationPtr ActivePresentation={ read=Get_ActivePresentation }; // 0, Yes
  __property Powerpoint_2k::SlideShowWindowsPtr SlideShowWindows={ read=Get_SlideShowWindows }; // 0, Yes
  __property Office_2k::CommandBarsPtr CommandBars={ read=Get_CommandBars }; // 0, Yes
  __property BSTR Path={ read=Get_Path }; // 0, No
  __property BSTR Name={ read=Get_Name }; // 0, No
  __property Office_2k::AssistantPtr Assistant={ read=Get_Assistant }; // 0, Yes
  __property Office_2k::FileSearchPtr FileSearch={ read=Get_FileSearch }; // 0, Yes
  __property Office_2k::IFindPtr FileFind={ read=Get_FileFind }; // 0, Yes
  __property BSTR Build={ read=Get_Build }; // 0, No
  __property BSTR Version={ read=Get_Version }; // 0, No
  __property BSTR OperatingSystem={ read=Get_OperatingSystem }; // 0, No
  __property BSTR ActivePrinter={ read=Get_ActivePrinter }; // 0, No
  __property long Creator={ read=Get_Creator }; // 0, No
  __property Powerpoint_2k::AddInsPtr AddIns={ read=Get_AddIns }; // 0, Yes
  __property Vbide_2k::VBEPtr VBE={ read=Get_VBE }; // 0, Yes
  __property Office_2k::MsoTriState Active={ read=Get_Active }; // 0, No
  __property Office_2k::AnswerWizardPtr AnswerWizard={ read=Get_AnswerWizard }; // 0, Yes
  __property Office_2k::COMAddInsPtr COMAddIns={ read=Get_COMAddIns }; // 0, Yes
  __property BSTR ProductCode={ read=Get_ProductCode }; // 0, No
  __property Powerpoint_2k::DefaultWebOptionsPtr DefaultWebOptions={ read=Get_DefaultWebOptions }; // 0, Yes
  __property Office_2k::LanguageSettingsPtr LanguageSettings={ read=Get_LanguageSettings }; // 0, Yes
  __property Office_2k::MsoDebugOptionsPtr MsoDebugOptions={ read=Get_MsoDebugOptions }; // 0, Yes
  __property Powerpoint_2k::MarkerPtr Marker={ read=Get_Marker }; // 0, Yes
  /*CoClassWriteProperties*/
  __property BSTR Caption={ read=Get_Caption, write=Set_Caption, stored=false }; // 0, No
  __property float Left={ read=Get_Left, write=Set_Left, stored=false }; // 0, No
  __property float Top={ read=Get_Top, write=Set_Top, stored=false }; // 0, No
  __property float Width={ read=Get_Width, write=Set_Width, stored=false }; // 0, No
  __property float Height={ read=Get_Height, write=Set_Height, stored=false }; // 0, No
  __property Powerpoint_2k::PpWindowState WindowState={ read=Get_WindowState, write=Set_WindowState, stored=false }; // 0, No
  __property Office_2k::MsoTriState Visible={ read=Get_Visible, write=Set_Visible, stored=false }; // 0, No
  __property Office_2k::MsoTriState ShowWindowsInTaskbar={ read=Get_ShowWindowsInTaskbar, write=Set_ShowWindowsInTaskbar, stored=false }; // 0, No
  __property Office_2k::MsoFeatureInstall FeatureInstall={ read=Get_FeatureInstall, write=Set_FeatureInstall, stored=false }; // 0, No
  /*CoClassWriteEventDecls*/
private:
  TPowerPointApplicationWindowSelectionChange FOnWindowSelectionChange;
  TPowerPointApplicationWindowBeforeRightClick FOnWindowBeforeRightClick;
  TPowerPointApplicationWindowBeforeDoubleClick FOnWindowBeforeDoubleClick;
  TPowerPointApplicationPresentationClose FOnPresentationClose;
  TPowerPointApplicationPresentationSave FOnPresentationSave;
  TPowerPointApplicationPresentationOpen FOnPresentationOpen;
  TPowerPointApplicationNewPresentation FOnNewPresentation;
  TPowerPointApplicationPresentationNewSlide FOnPresentationNewSlide;
  TPowerPointApplicationWindowActivate FOnWindowActivate;
  TPowerPointApplicationWindowDeactivate FOnWindowDeactivate;
  TPowerPointApplicationSlideShowBegin FOnSlideShowBegin;
  TPowerPointApplicationSlideShowNextBuild FOnSlideShowNextBuild;
  TPowerPointApplicationSlideShowNextSlide FOnSlideShowNextSlide;
  TPowerPointApplicationSlideShowEnd FOnSlideShowEnd;
  TPowerPointApplicationPresentationPrint FOnPresentationPrint;
__published:
  __property TPowerPointApplicationWindowSelectionChange OnWindowSelectionChange={ read=FOnWindowSelectionChange, write=FOnWindowSelectionChange };
  __property TPowerPointApplicationWindowBeforeRightClick OnWindowBeforeRightClick={ read=FOnWindowBeforeRightClick, write=FOnWindowBeforeRightClick };
  __property TPowerPointApplicationWindowBeforeDoubleClick OnWindowBeforeDoubleClick={ read=FOnWindowBeforeDoubleClick, write=FOnWindowBeforeDoubleClick };
  __property TPowerPointApplicationPresentationClose OnPresentationClose={ read=FOnPresentationClose, write=FOnPresentationClose };
  __property TPowerPointApplicationPresentationSave OnPresentationSave={ read=FOnPresentationSave, write=FOnPresentationSave };
  __property TPowerPointApplicationPresentationOpen OnPresentationOpen={ read=FOnPresentationOpen, write=FOnPresentationOpen };
  __property TPowerPointApplicationNewPresentation OnNewPresentation={ read=FOnNewPresentation, write=FOnNewPresentation };
  __property TPowerPointApplicationPresentationNewSlide OnPresentationNewSlide={ read=FOnPresentationNewSlide, write=FOnPresentationNewSlide };
  __property TPowerPointApplicationWindowActivate OnWindowActivate={ read=FOnWindowActivate, write=FOnWindowActivate };
  __property TPowerPointApplicationWindowDeactivate OnWindowDeactivate={ read=FOnWindowDeactivate, write=FOnWindowDeactivate };
  __property TPowerPointApplicationSlideShowBegin OnSlideShowBegin={ read=FOnSlideShowBegin, write=FOnSlideShowBegin };
  __property TPowerPointApplicationSlideShowNextBuild OnSlideShowNextBuild={ read=FOnSlideShowNextBuild, write=FOnSlideShowNextBuild };
  __property TPowerPointApplicationSlideShowNextSlide OnSlideShowNextSlide={ read=FOnSlideShowNextSlide, write=FOnSlideShowNextSlide };
  __property TPowerPointApplicationSlideShowEnd OnSlideShowEnd={ read=FOnSlideShowEnd, write=FOnSlideShowEnd };
  __property TPowerPointApplicationPresentationPrint OnPresentationPrint={ read=FOnPresentationPrint, write=FOnPresentationPrint };
private:
  bool     FAutoQuit;
__published:
  __property bool AutoQuit = {read=FAutoQuit, write=FAutoQuit};
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TMaster
// Help String      : 
// Default Interface: _Master
// Def. Intf. Object: _MasterPtr
// Def. Intf. DISP? : No
// Event   Interface: MasterEvents
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TMaster : public Oleserver::TOleServer
{
  _MasterPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TMaster(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  _MasterPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(_MasterPtr intf);

  virtual void __fastcall InvokeEvent(int DispID, TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
  Powerpoint_2k::PowerPointApplicationPtr __fastcall Get_Application(void)
  {
    return GetDefaultInterface()->get_Application();
  }

  LPDISPATCH __fastcall Get_Parent(void)
  {
    return GetDefaultInterface()->get_Parent();
  }

  Powerpoint_2k::ShapesPtr __fastcall Get_Shapes(void)
  {
    return GetDefaultInterface()->get_Shapes();
  }

  Powerpoint_2k::HeadersFootersPtr __fastcall Get_HeadersFooters(void)
  {
    return GetDefaultInterface()->get_HeadersFooters();
  }

  Powerpoint_2k::ColorSchemePtr __fastcall Get_ColorScheme(void)
  {
    return GetDefaultInterface()->get_ColorScheme();
  }

  void __fastcall Set_ColorScheme(Powerpoint_2k::ColorSchemePtr ColorScheme/*[in]*/)
  {
    GetDefaultInterface()->set_ColorScheme(ColorScheme/*[in]*/);
  }

  Powerpoint_2k::ShapeRangePtr __fastcall Get_Background(void)
  {
    return GetDefaultInterface()->get_Background();
  }

  BSTR __fastcall Get_Name(void)
  {
    return GetDefaultInterface()->get_Name();
  }

  void __fastcall Set_Name(BSTR Name/*[in]*/)
  {
    GetDefaultInterface()->set_Name(Name/*[in]*/);
  }

  float __fastcall Get_Height(void)
  {
    return GetDefaultInterface()->get_Height();
  }

  float __fastcall Get_Width(void)
  {
    return GetDefaultInterface()->get_Width();
  }

  Powerpoint_2k::TextStylesPtr __fastcall Get_TextStyles(void)
  {
    return GetDefaultInterface()->get_TextStyles();
  }

  Powerpoint_2k::HyperlinksPtr __fastcall Get_Hyperlinks(void)
  {
    return GetDefaultInterface()->get_Hyperlinks();
  }

  Office_2k::ScriptsPtr __fastcall Get_Scripts(void)
  {
    return GetDefaultInterface()->get_Scripts();
  }

  /*CoClassWriteMethods*/
  void __fastcall Delete(void)
  {
    GetDefaultInterface()->Delete();
  }

  /*CoClassWriteProperties*/
  __property Powerpoint_2k::PowerPointApplicationPtr Application={ read=Get_Application }; // 0, Yes
  __property LPDISPATCH Parent={ read=Get_Parent }; // 0, No
  __property Powerpoint_2k::ShapesPtr Shapes={ read=Get_Shapes }; // 0, Yes
  __property Powerpoint_2k::HeadersFootersPtr HeadersFooters={ read=Get_HeadersFooters }; // 0, Yes
  __property Powerpoint_2k::ShapeRangePtr Background={ read=Get_Background }; // 0, Yes
  __property float Height={ read=Get_Height }; // 0, No
  __property float Width={ read=Get_Width }; // 0, No
  __property Powerpoint_2k::TextStylesPtr TextStyles={ read=Get_TextStyles }; // 0, Yes
  __property Powerpoint_2k::HyperlinksPtr Hyperlinks={ read=Get_Hyperlinks }; // 0, Yes
  __property Office_2k::ScriptsPtr Scripts={ read=Get_Scripts }; // 0, Yes
  /*CoClassWriteProperties*/
  __property Powerpoint_2k::ColorSchemePtr ColorScheme={ read=Get_ColorScheme, write=Set_ColorScheme, stored=false }; // 0, Yes
  __property BSTR Name={ read=Get_Name, write=Set_Name, stored=false }; // 0, No
  /*CoClassWriteEventDecls*/
private:
__published:
};

};     // namespace Powerpoint_2k

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Powerpoint_2k;
#endif

#pragma option pop

#endif // __PowerPoint_2K_SRVR_h__
