// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.0.1.3  $
// File generated on 1/24/2000 09:46:10 AM from Type Library described below.

// ************************************************************************ //
// Type Lib: D:\Program Files\Common Files\Microsoft Shared\VBA\VBA6\VBE6EXT.OLB (1)
// IID\LCID: {0002E157-0000-0000-C000-000000000046}\0
// Helpfile: D:\Program Files\Common Files\Microsoft Shared\VBA\VBA6\vbob6.chm
// DepndLst: 
//   (1) v2.0 stdole, (D:\WINNT\System32\stdole2.tlb)
//   (2) v2.1 Office, (D:\msof2k\Office\mso9.dll)
// Parent TypeLibrary:
//   (0) v2.6 PowerPoint, (d:\tlbgen\rampage\typelib\TypeLibraries\MSPPT9.olb)
// ************************************************************************ //
#ifndef   __VBIDE_2K_SRVR_h__
#define   __VBIDE_2K_SRVR_h__

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0500)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "Office_2K.h"

#include "VBIDE_2K.h"
namespace Vbide_2k
{

// *********************************************************************//
// HelpString: Microsoft Visual Basic for Applications Extensibility 5.3
// Version:    5.3
// *********************************************************************//

};     // namespace Vbide_2k

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Vbide_2k;
#endif

#pragma option pop

#endif // __VBIDE_2K_SRVR_h__
