// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.21  $
// File generated on 1/28/2002 7:56:10 AM from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files\Common Files\Microsoft Shared\VBA\VBEEXT1.OLB (1)
// LIBID: {0002E157-0000-0000-C000-000000000046}
// LCID: 0
// Helpfile: C:\Program Files\Common Files\Microsoft Shared\VBA\VEENOB3.HLP
// HelpString: Microsoft Visual Basic for Applications Extensibility
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
//   (2) v2.0 Office, (C:\Program Files\Microsoft Office\office97\Office\MSO97.DLL)
// Parent TypeLibrary:
//   (0) v1.2 Excel, (c:\program files\microsoft office\office\excel8.olb)
// ************************************************************************ //
#ifndef   VBIDE_97_SRVRH
#define   VBIDE_97_SRVRH

#pragma option push -b -w-inl

#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "Office_97.h"

#include "VBIDE_97.h"
namespace Vbide_97
{

// *********************************************************************//
// HelpString: Microsoft Visual Basic for Applications Extensibility
// Version:    5.0
// *********************************************************************//

};     // namespace Vbide_97

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Vbide_97;
#endif

#pragma option pop

#endif // VBIDE_97_SRVRH
