// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.0.1.0.1.2  $
// File generated on 1/29/2002 1:29:48 PM from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files\Common Files\Microsoft Shared\VBA\VBA6\VBE6EXT.OLB (1)
// LIBID: {0002E157-0000-0000-C000-000000000046}
// LCID: 0
// Helpfile: C:\Program Files\Common Files\Microsoft Shared\VBA\VBA6\vbob6.chm
// HelpString: Microsoft Visual Basic for Applications Extensibility 5.3
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\stdole2.tlb)
//   (2) v2.2 Office, (C:\Program Files\Common Files\Microsoft Shared\Office10\MSO.DLL)
// Parent TypeLibrary:
//   (0) v5.0 FrontPage, (c:\program files\microsoft office\office10\frontpg.exe)
// ************************************************************************ //
#ifndef   VBIDE_XP_srvrH
#define   VBIDE_XP_srvrH

#pragma option push -b -w-inl

#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>
#include "Office_XP.h"

#include "VBIDE_XP.h"
namespace Vbide_xp
{

// *********************************************************************//
// HelpString: Microsoft Visual Basic for Applications Extensibility 5.3
// Version:    5.3
// *********************************************************************//

};     // namespace Vbide_xp

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Vbide_xp;
#endif

#pragma option pop

#endif // VBIDE_XP_srvrH
