#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------
EXERES  = applaunc
HLP     = applaunc
HLP_    = applaunc.rtf
RESEXE_ = applaunc.rh
EXEALL  = applaunc.exe exitwin.exe
EXEMAKE = $(APPLAUNC) $(EXITWIN)
EXITWINX= $(EXERULE:applaunc=exitwin)
EXITWIN = $(EXITWINX:$(SYSLIBS)=)
APPLAUNC= $(EXERULE:applaunc.obj=appmgr.obj appbtn.obj appbtnba.obj\
                                 dialogs.obj appwin.obj applaunc.obj)
MODELS = mldf
!include $(BCEXAMPLEDIR)\owlmake.gen
