#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\multipad\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = multipad
CPCH    = -Hc -H"windows.h" -H=multipad.csm
OBJEXE  = multipad.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          file.obj filedlg.obj finddlg.obj mdichild.obj print.obj\
          printdlg.obj search.obj statbar.obj toolbar.obj

!include $(BCEXAMPLEDIR)\makefile.gen
