#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1993, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES = modalwin
OBJEXE = modalwin.obj
MODELS = ldft

!include $(BCEXAMPLEDIR)\owlmake.gen
