//----------------------------------------------------------------------------
// ObjectWindows - (c) Copyright 1991, 1996 by Borland International
//----------------------------------------------------------------------------
#if !defined(__MODALWIN_H)
#define __MODALWIN_H

#define CM_MWABOUT          104
#define CM_DABOUT           105
#define CM_APPMODAL_CHILD   107
#define CM_TASKMODAL_CHILD  108
#define CM_SYSMODAL_CHILD   109

#define IDA_MODALWIN        500     // Accelerator
#define IDI_MODALWIN       1000     // Icon
#define IDM_MODALWIN       1000     // Menu
#define IDD_ABOUT          1000     // AboutBox Dialog

#endif
