#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES=dragdrop
!include $(BCEXAMPLEDIR)\owlmake.gen
