#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.3  $                                                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =               \
        clreol.obj   \
        clrscr.obj   \
        crtinit.obj  \
        cursor.obj   \
        getch.obj    \
        getche.obj   \
        kbhit.obj    \
        movecurs.obj \
        movetext.obj \
        scroll.obj   \
        vram.obj     \
        _wherexy.obj

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
!include rules.mak

