#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES=bmpview
MODELS=ldf
!include $(BCEXAMPLEDIR)\owlmake.gen

