/*
 *      C/C++ Run Time Library - Version 10.0
 *
 *      Copyright (c) 1996, 2000 by Inprise Corporation
 *      All Rights Reserved.
 *
 */

/* $Revision:   9.0  $ */

#include <_tchar.h>
/*----------------------------------------------------------------------
 * Public variables - dummy version for RTLDLL so that linker can
 *                    resolve forced symbols
 */
int _tsetenvp__ = 0;                    /* satisfy ext. ref. generated by BCC32 */

