/*
 *      C/C++ Run Time Library - Version 11.0
 *
 *      Copyright (c) 1996, 2002 by Borland Software Corporation
 *      All Rights Reserved.
 *
 */

/* $Revision: 9.3 $ */

#include <_tchar.h>
/*----------------------------------------------------------------------
 * Public variables - dummy version for RTLDLL so that linker can
 *                    resolve forced symbols
 */
int _tsetenvp__ = 0;                    /* satisfy ext. ref. generated by BCC32 */

