#----------------------------------------------------------------------------
# Owl
# Copyright (c) 1996, 1996 by Borland International, All Rights Reserved
#
#   Usage:
#     make MODEL={f|d}   WIN32=1      for 32-bit Windows
#     make MODEL={m|l|d} WIN16=1      for 16-bit Windows
#----------------------------------------------------------------------------
SYSTEMS = WIN16 WIN32
EXERES  = VerInfo
OBJEXE  = VerInfo.obj
!include $(BCEXAMPLEDIR)\owlmake.gen
