#-----------------------------------------------------------------------------
# Turbo Profiler - (C) Copyright 1994 by Borland International
#
#       MAKEFILE to build all the Turbo Profiler Samples
#
# The following models may be defined on command line or environment:
#   16-bit small   model:  make MODEL=s  
#   16-bit medium  model:  make MODEL=m  
#   16-bit compact model:  make MODEL=c  
#   16-bit large   model:  make MODEL=l  
#   16-bit huge    model:  make MODEL=h  
#
# Specify TARGET=xxxx.exe to build only one target sample, rather than all.
#   For example:
#           MAKE  TARGET=prime1.exe
#-----------------------------------------------------------------------------
!if !$d(DEBUG)          # Define DEBUG=0 to disable DEBUG information
DEBUG=1                 # Define to build with debug information
!endif

MODELS=smclh
SYSTEM=DOS16
EXE = sample
EXEALL= calltest.exe plost.exe prime0.exe prime1.exe prime2.exe \
        prime3.exe prime4.exe prime5.exe ptoll.exe

EXEMAKE= $(CALLTEST) $(PLOST)  $(PRIME0) $(PRIME1) $(PRIME2) \
         $(PRIME3)   $(PRIME4) $(PRIME5) $(PTOLL)

CALLTEST=$(EXERULE:sample=calltest)
PLOST=$(EXERULE:sample=plost)
PRIME0=$(EXERULE:sample=prime0)
PRIME1=$(EXERULE:sample=prime1)
PRIME2=$(EXERULE:sample=prime2)
PRIME3=$(EXERULE:sample=prime3) 
PRIME4=$(EXERULE:sample=prime4) 
PRIME5=$(EXERULE:sample=prime5) 
PTOLL=$(EXERULE:sample=ptoll)

!include $(BCEXAMPLEDIR)\makefile.gen
