# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992-1995 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.


OBJS=stdafx.obj localctl.obj localize.obj localppg.obj

USES_OLE=1
AFXDLL=1
PROJ = localize
USRDLL=1

All: locresfr.dll locresde.dll MainRule
        @-if exist $(PROJ).ocx del $(PROJ).ocx
	@-ren $(PROJ).dll $(PROJ).ocx

locresfr.dll:
	make -flocresfr.mak

locresde.dll:
	make -flocresde.mak

!include <$(MAKEDIR)\..\include\mfc\mfcsamps.mak>

