#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for Hash Table examples                                       #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l}     -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

!if $(SYSTEM)==WIN16 || $d(WIN16) || $(SYSTEM)==DOS16 || $d(DOS16) || !$d(SYSTEM)
 MODELS = mlh
!endif
SYSTEMS = DOS16 WIN16 CON32

EXE    = hash
EXEALL = hash.exe ihash.exe

EXEMAKE= $(HASH) $(IHASH)

RULES  = myclass.obj: ..\myclass.cpp

HASH=$(EXERULE:hash.obj=hash.obj myclass.obj)
IHASH=$(HASH:hash=ihash)


!include $(BCEXAMPLEDIR)\bidsmake.gen

