#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1995 by Borland International
#----------------------------------------------------------------------------

MODELS=lfd
EXE=sysmetri
!include $(BCEXAMPLEDIR)\owlmake.gen


