#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = lfd
EXERES = progmanx
!include $(BCEXAMPLEDIR)\owlmake.gen
