//----------------------------------------------------------------------------
// ObjectWindows - (C) Copyright 1991, 1993 by Borland International
//   Resource & command IDs
//----------------------------------------------------------------------------

#define IDD_PROGTALK  100

//#define IDD_DDEDIALOG    100
//#define IDD_ADDDIALOG    101
//#define IDD_CREATEDIALOG 102

// DDE dialog item IDs

#define ID_LISTBOX      100
#define CM_ADDITEM      101
#define CM_DELETEITEM   102
#define CM_CLEARITEMS   103
#define CM_CREATEGROUP  104
