#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldft

EXERES = splitter

!include $(BCEXAMPLEDIR)\owlmake.gen
