#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1992 by Borland International
#----------------------------------------------------------------------------

EXERES = ttt
!include $(BCEXAMPLEDIR)\owlmake.gen
