#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for DATE example                                              #
#                                                                          #
#   Copyright (c) 1994 Borland International                               #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#                                                                          #
#       make                            for 32-bit Windows Console         #
#                                                                          #
#--------------------------------------------------------------------------#

SYSTEMS= CON32
EXE    = thread
CON32  = 1

!include $(BCEXAMPLEDIR)\bidsmake.gen

