#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for threads example                                           #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#                                                                          #
#--------------------------------------------------------------------------#

SYSTEMS= CON32
EXE    = thread
CON32  = 1

!include $(BCEXAMPLEDIR)\bidsmake.gen

