#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.8  $                                                       #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =               \
        alloca.obj   \
        chkstk.obj   \
        memchk.obj   \
        stkavail.obj \
        calloc.obj   \
        del.obj      \
        delarray.obj \
        new.obj      \
        newarray.obj \
        newpl.obj    \
        newplarr.obj \
	setnew.obj   \
        vapp.obj     \
        vappv.obj    \
        vdel.obj     \
        vdelldtc.obj \
        vnewldtc.obj \
        vnwvldtc.obj

!if $d(MAGIC)
OBJS = $(OBJS)	     \
        pheap.obj    
!else
OBJS = $(OBJS)	     \
        heap.obj     \
        heapchk.obj  \
        heapchkf.obj \
        heapchkn.obj \
        heapfill.obj \
        heapmin.obj  \
        heapset.obj  \
        heapwalk.obj \
        oheapchk.obj \
        oheapwlk.obj \
	realloc.obj
!endif

!if $d(DLL)
    IMPOBJS =            \
            chkstk.obj   \
            vdel.obj     \
            vdelldtc.obj \
            vnewldtc.obj \
            vnwvldtc.obj
!endif

    MISC =		\
            setnewnx.obj

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

#############################################################################
# MISC explicit rules.                                                      #
#############################################################################
setnewnx.obj : setnew.cpp
    $(CC) -o$(OBJDIR)\$& -DNOXX $?
