#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES=peeper
MODELS=ldf
!include $(BCEXAMPLEDIR)\owlmake.gen

