#----------------------------------------------------------------------------
# ObjectComponents
# Copyright (c) 1994, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
!if "$(MODEL)" == "f"

EXE    = regist32
OBJEXE = register.obj 
RESEXE = register.res

!else

!if !$d(MODEL)
MODEL = l
!endif
MODELS = ml
EXERES = register
#DOSSTUB= wrw.stb

!endif

!include $(BCEXAMPLEDIR)\ocfmake.gen



