#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for Stack examples                                            #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l}     -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

!if $(SYSTEM)==WIN16 || $d(WIN16) || $(SYSTEM)==DOS16 || $d(DOS16) || !$d(SYSTEM)
 MODELS = mlh
!endif
SYSTEMS = DOS16 WIN16 CON32

EXE    = stack
EXEALL = stack.exe istack.exe stklist.exe istklist.exe

EXEMAKE= $(STACK) $(ISTACK) $(STKLIST) $(ISTKLIST)

RULES  = myclass.obj: ..\myclass.cpp

STACK=$(EXERULE:stack.obj=stack.obj myclass.obj)
ISTACK=$(STACK:stack=istack)
STKLIST=$(STACK:stack=stklist)
ISTKLIST=$(STACK:stack=istklist)


!include $(BCEXAMPLEDIR)\bidsmake.gen

