#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#   examples\owl\owlapi\instance\makefile
#----------------------------------------------------------------------------

EXE = instance
!include $(BCEXAMPLEDIR)\owlmake.gen

