//----------------------------------------------------------------------------
// ObjectWindows - (C) Copyright 1992, 1993 by Borland International
//   include\owl\owlcore.h
//   Include for the core classes in Owl.  Works well with precompiled hdrs
//----------------------------------------------------------------------------
#if !defined(__OWL_OWLCORE_H)
#define __OWL_OWLCORE_H

#include <owl\owldefs.h>
#include <owl\version.h>

#include <owl\module.h>
#include <owl\applicat.h>

#include <owl\dc.h>
#include <owl\menu.h>

#include <owl\window.h>

#include <owl\mdi.h>
#include <owl\mdichild.h>
#include <owl\decmdifr.h>

#include <owl\dialog.h>
#include <owl\control.h>

#endif  // __OWL_OWLCORE_H
