//----------------------------------------------------------------------------
// ObjectWindows
// Copyright (c) 1995, 1997 by Borland International, All Rights Reserved
//
//$Revision:   10.4  $
//
// Backward compatible header
//----------------------------------------------------------------------------
#if !defined(OWL_OWLPCH_H)
#define OWL_OWLPCH_H

#if defined(NO_OWL2_COMPAT)
# pragma message owl/owlpch.h has been replaced by owl/pch.h
#endif
#if !defined(OWL_PCH_H)
# include <owl/pch.h>
#endif

#endif  //  OWL_OWLPCH_H
