//----------------------------------------------------------------------------
// ObjectWindows
// Copyright (c) 1991, 1996 by Borland International, All Rights Reserved
//
//$Revision:   10.3  $
//
// TUIHandle class definition [Backward compatible header]
//----------------------------------------------------------------------------
#if !defined(OWL_UIHANDLE_H)
#define OWL_UIHANDLE_H

#if defined(NO_OWL2_COMPAT)
# pragma message owl/uihandle.h has been replaced by owl/uihelper.h
#endif
#if !defined(OWL_UIHELPER_H)
# include <owl/uihelper.h>
#endif

#endif  // OWL_UIHANDLE_H
