#----------------------------------------------------------------------------
# ObjectComponents
# (C) Copyright 1994 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
!if !$d(MODEL)
MODEL = s
!endif
EXE    = dllrun  
DOSSTUB= wrw.stb

USERLIBS = $(BCLIBDIR)\ole2w16.lib
!include $(BCEXAMPLEDIR)\makefile.gen
