#----------------------------------------------------------------------------
# ObjectComponents
# Copyright (c) 1994, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = l
SYSTEMS = WIN16

!if !$d(MODEL)
MODEL = l
!endif

!if !$d(SYSTEM) 
SYSTEM = WIN16
!endif
 
EXE     = dllrun
#DOSSTUB= wrw.stb    #//!BB Where does this stub come from??
USERLIBPATH = $(BCLIBDIR)
USERLIBS = ole2w16.lib bidsl.lib

#
# should make look for BIDS somewhere other than BCROOT?
#
!if $d(BIDSINCDIR)
USERINCPATH=$(BIDSINCDIR)
!endif
!if $d(BIDSLIBDIR)
USERLIBPATH=$(BIDSLIBDIR);$(USERLIBPATH)
!endif

!include $(BCEXAMPLEDIR)\makefile.gen
