#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = df
SYSTEMS = WIN32

EXE = shell
LIBEXE = $(BCLIBDIR)\ole2w32.lib $(BCLIBDIR)\ctl3d32.lib
DEFEXE = shellapp.def
RESEXE = shellapp.res
OBJEXE = aboutdlg.obj shellapp.obj mdichild.obj mdiclien.obj shellwin.obj
OSMAJOR = 4
OSMINOR = 0

!include $(BCEXAMPLEDIR)\owlmake.gen

CFLAGS= $(CFLAGS) -D_OWLALLPCH -DINC_OLE2
