#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1993, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES=draw
OBJEXE=draw.obj
!include $(BCEXAMPLEDIR)\owlmake.gen

