#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES = listbox
OBJEXE = listboxx.obj
MODELS = ldft

!include $(BCEXAMPLEDIR)\owlmake.gen

