# Borland C++ - (C) Copyright 1993 by Borland International
# Makefile for TSTAPP & MSGWND program

SYSTEMS= WIN16 WIN32
EXERES = tstapp
OBJEXE = tstapp.obj ddesrvr.obj ddepack.obj  #note: ddesrvr.obj is really for msgwnd.exe
EXEALL = msgwnd.exe tstapp.exe
EXEMAKE= $(MSGWND) $(TSTAPP)

TSTAPP = $(EXERULE:ddesrvr.obj=ddeclnt.obj msgproc.obj)  # fix objs for tstapp
MSGWND = $(EXERULE:tstapp=msgwnd)                  # global replace for msgwnd
!include $(BCEXAMPLEDIR)\makefile.gen
