#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\windows\tstapp\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
CPCH    = -Hc -H"windows.h" -H=tstapp.csm
EXERES  = tstapp
OBJEXE  = tstapp.obj ddesrvr.obj ddepack.obj  #note: ddesrvr.obj is really for msgwnd.exe
EXEALL  = msgwnd.exe tstapp.exe
EXEMAKE = $(MSGWND) $(TSTAPP)

TSTAPP  = $(EXERULE:ddesrvr.obj=ddeclnt.obj msgproc.obj)  # fix objs for tstapp
MSGWND  = $(EXERULE:tstapp=msgwnd)                  # global replace for msgwnd

!include $(BCEXAMPLEDIR)\makefile.gen
