#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for association examples                                      #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l}     -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

!if $(SYSTEM)==WIN16 || $d(WIN16) || $(SYSTEM)==DOS16 || $d(DOS16) || !$d(SYSTEM)
 MODELS = mlh
!endif
SYSTEMS = DOS16 WIN16 CON32

EXE    = assocdd
EXEALL = assocdd.exe assocdi.exe associd.exe associi.exe associdd.exe

EXEMAKE= $(ASSOCDD) $(ASSOCDI) $(ASSOCID) $(ASSOCII) $(ASSOCIDD)

RULES  = myclass.obj: ..\myclass.cpp

ASSOCDD=$(EXERULE:assocdd.obj=assocdd.obj myclass.obj)
ASSOCDI=$(ASSOCDD:assocdd=assocdi)
ASSOCID=$(ASSOCDD:assocdd=associd)
ASSOCII=$(ASSOCDD:assocdd=associi)
ASSOCIDD=$(ASSOCDD:assocdd=associdd)


!include $(BCEXAMPLEDIR)\bidsmake.gen

