#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

!if !$d(MODEL)
  MODEL=l
!endif

EXERES  =dynmnu
OBJEXE  =app.obj dynmnu.obj dmdecfr.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
