#==========================================================================
#
#  makefile - makefile for examples
#
#==========================================================================
#
#  (c) Copyright 1994, 1995 Rogue Wave Software, Inc.
#  ALL RIGHTS RESERVED
#
#  The software and information contained herein are proprietary to, and
#  comprise valuable trade secrets of, Rogue Wave Software, Inc., which
#  intends to preserve as trade secrets such software and information.
#  This software is furnished pursuant to a written license agreement and
#  may be used, copied, transmitted, and stored only in accordance with
#  the terms of such license and with the inclusion of the above copyright
#  notice.  This software and information or any other copies thereof may
#  not be provided or otherwise made available to any other person.
#
#  Notwithstanding any other lease or license that may pertain to, or
#  accompany the delivery of, this computer software and information, the
#  rights of the Government regarding its use, reproduction and disclosure
#  are as set forth in Section 52.227-19 of the FARS Computer
#  Software-Restricted Rights clause.
#
#  Use, duplication, or disclosure by the Government is subject to
#  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in
#  Technical Data and Computer Software clause at DFARS 252.227-7013.
#  Contractor/Manufacturer is Rogue Wave Software, Inc.,
#  P.O. Box 2328, Corvallis, Oregon 97339.
#
#  This computer software and information is distributed with "restricted
#  rights."  Use, duplication or disclosure is subject to restrictions as
#  set forth in NASA FAR SUP 18-52.227-79 (April 1985) "Commercial
#  Computer Software-Restricted Rights (April 1985)."  If the Clause at
#  18-52.227-74 "Rights in Data General" is specified in the contract,
#  then the "Alternate III" clause applies.
#
#==========================================================================
#
#  Makefile for the Rogue Wave Standard Library package, using
#  Borland C++ with a Win32 target.
#
#  Note ONLY the Borland-supplied "make" command
#  should be used.
#
#==========================================================================

!include makeincl.inc

########################   Targets    #################################

all : accum.exe adj_diff.exe advance.exe auto_ptr.exe b_search.exe \
	binders.exe bitset.exe complex.exe copyex.exe count.exe \
	deque.exe distance.exe eqlrange.exe equal.exe exceptio.exe \
	exceptn.exe fill.exe find.exe find_f_o.exe for_each.exe \
	funct_ob.exe generate.exe heap_ops.exe includes.exe \
	inr_prod.exe ins_itr.exe lex_comp.exe limits.exe list.exe \
        map.exe max.exe max_elem.exe merge.exe mismatch.exe \
	multimap.exe multiset.exe negator.exe nthelem.exe p_queue.exe \
	partsort.exe partsum.exe permute.exe pnt2fnct.exe prtition.exe \
	queue.exe remove.exe replace.exe rev_itr.exe reverse.exe \
	rndshufl.exe rotate.exe search.exe setex.exe set_diff.exe \
	set_intr.exe set_unin.exe set_s_di.exe set_intr.cpp sort.exe \
	stack.exe string.exe swap.exe trnsform.exe ul_bound.exe \
	unique.exe vector.exe alg1.exe alg2.exe alg3.exe alg4.exe \
	alg5.exe alg6.exe alg7.exe calc.exe complx.exe concord.exe \
	graph.exe icecream.exe radix.exe sieve.exe spell.exe tele.exe \
	widwork.exe


clean:
   if exist *.obj del *.obj
   if exist *.exe del *.exe

###########################  Implicit Rules #######################
.cpp.obj:
    $(CPP) $(CPPFLAGS) -c {$< }

.obj.exe:
    $(CPP) $(CPPFLAGS) $<
