#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for QUEUE examples                                            #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l}     -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

!if $(SYSTEM)==WIN16 || $d(WIN16) || $(SYSTEM)==DOS16 || $d(DOS16) || !$d(SYSTEM)
 MODELS = mlh
!endif
SYSTEMS = DOS16 WIN16 CON32

EXE    = queue
EXEALL = queue.exe iqueue.exe quelist.exe iquelist.exe

EXEMAKE= $(QUEUE) $(IQUEUE) $(QUELIST) $(IQUELIST)

RULES  = myclass.obj: ..\myclass.cpp

QUEUE=$(EXERULE:queue.obj=queue.obj myclass.obj)
IQUEUE=$(QUEUE:queue=iqueue)

QUELIST=$(QUEUE:queue=quelist)
IQUELIST=$(QUEUE:queue=iquelist)

!include $(BCEXAMPLEDIR)\bidsmake.gen

