#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES=mdistrm
MODELS=mldf
!include $(BCEXAMPLEDIR)\owlmake.gen
