#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldft
EXERES = transfer

!include $(BCEXAMPLEDIR)\owlmake.gen
