//----------------------------------------------------------------------------
// ObjectWindows
// Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
//----------------------------------------------------------------------------
#define IDC_HSCROLL1        100
#define IDC_PUSHBUTTON1     101
#define IDC_PUSHBUTTON2     102
#define IDC_AUTOCHECKBOX1   103
#define IDC_AUTOCHECKBOX2   104
#define IDC_AUTOCHECKBOX3   105
#define IDC_EDIT1           106
#define IDC_EDIT2           107
#define IDC_LISTBOX1        108
#define IDC_DROPDOWNLIST1   109
#define ID_MENU             110
#define CM_DIALOG           111
#define CM_TRANSFER         112
#define CM_ADDLISTBOX       113
#define CM_ADDCOMBOBOX      114

#define IDD_DIALOG          200
#define ID_MRBUTTON         201
#define ID_MSBUTTON         202
#define ID_DRBUTTON         203
#define ID_NAMEEDIT         204
#define ID_ADDR1EDIT        205
#define ID_ADDR2EDIT        206
#define ID_CITYSTEDIT       207
#define ID_COUNTRYEDIT      208
#define ID_CHECKBOX1        209
#define ID_CHECKBOX2        210
#define ID_CHECKBOX3        211
#define ID_LISTBOX          212
#define ID_LISTBOXDATA      213
#define ID_COMBOBOX         214
#define ID_COMBOBOXDATA     215
#define ID_SCROLLBAR        216

#define ID_DISPLAY_INFO     300
#define ID_INFO             301

