#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.15  $                                                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =               \
        wdirect.obj  \
        direct.obj   \
	chdir.obj    \
        chdrive.obj  \
        chmod.obj    \
        dosclose.obj \
        doscreat.obj \
        dosdfree.obj \
        dosfattr.obj \
        dosfind.obj  \
        dosgdriv.obj \
        dosgftim.obj \
        dosopen.obj  \
        dosread.obj  \
        dossftim.obj \
        doswrite.obj \
        flength.obj  \
        fstat.obj    \
        fullpath.obj \
        getcurdi.obj \
        wgetcurd.obj \
        getdcwd.obj  \
        wgetdcwd.obj \
        getdfree.obj \
        getdisk.obj  \
        handles.obj  \
        ioerror.obj  \
        lock.obj     \
        locking.obj  \
        mkdir.obj    \
        oshandle.obj \
        rename.obj   \
        rmdir.obj    \
        _stat.obj     \
        stat.obj     \
        stati64.obj  \
        utime.obj    \
        wchdir.obj   \
        wchmod.obj   \
        wdscreat.obj \
        wfullpth.obj \
        wmkdir.obj   \
        wrename.obj  \
        wrmdir.obj   \
        wstat.obj    \
        wstati64.obj \
        wutime.obj   \
        _chmod.obj   \
        _close.obj   \
        _open.obj    \
        _pipe.obj    \
        _read.obj    \
        _wopen.obj   \
        _write.obj   \
        _waccess.obj \
        _wchmod.obj  \
        __access.obj \
        __close.obj  \
        __dup.obj    \
        __dup2.obj   \
        __ftrunc.obj \
        __isatty.obj \
        __lseek.obj  \
        __open.obj   \
        __wopen.obj  \
        _rmdir.obj   \
        _mkdir.obj   \
        _utime.obj   \
        unlink.obj   \
        wunlink.obj

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

wfullpth.obj : fullpath.c
_waccess.obj : __access.c
wchmod.obj   : chmod.c
_wchmod.obj  : _chmod.c
__wopen.obj  : __open.c
_wunlnk.obj  : unlink.c
wrename.obj  : rename.c
wgetcurd.obj : getcurdi.c
wgetdcwd.obj : getdcwd.c
wchdir.obj   : chdir.c
wmkdir.obj   : mkdir.c
wrmdir.obj   : rmdir.c
wstat.obj    : stat.c
wutime.obj   : utime.c
wdscreat.obj : doscreat.c
_wopen.obj   : _open.c
