#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES = tabctrl
OBJEXE = tabctrlx.obj
!include $(BCEXAMPLEDIR)\owlmake.gen
