#-----------------------------------------------------------------------------
# Borland C++ - (C) Copyright 1996 by Borland International
#   examples\vdbt\fishfact\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32

!ifndef SYSTEM
SYSTEM = WIN32
!endif

!ifndef MODEL
MODEL = d
!endif

!if $(SYSTEM)==WIN16
MODELS = d l
USERLIBS = $(BCLIBDIR)\bivbx.lib
DEFEXE = ffact16.def
!else
MODELS = d f
USERLIBS = $(BCLIBDIR)\bivbx32.lib
DEFEXE = ffact32.def
!endif

EXERES = fishfact
OBJEXE = ffactwin.obj fshtdlgc.obj
RESEXE = ffactwin.res
!include $(BCEXAMPLEDIR)\owlmake.gen
