#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for BIDS examples                                             #
#                                                                          #
#   Copyright (c) 1993 Borland International                               #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#                                                                          #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l} -DDOS16     for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

EXE     = labels

!include $(BCEXAMPLEDIR)\bidsmake.gen
