#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldft

EXE    = scrollba
OBJEXE = scrollbx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
