#define IDH_CM_CREATECHILD      101
#define IDH_CM_CASCADECHILDREN  102
#define IDH_CM_TILECHILDREN     103
#define IDH_CM_ARRANGEICONS     104
#define IDH_CM_CLOSECHILDREN    105

#define IDH_DLG_IDC_NAME	      201
#define IDH_DLG_IDC_PHONE	      202
#define IDH_DLG_IDC_NUMBER	    203
#define IDH_DLG_IDOK            204
#define IDH_DLG_IDCANCEL        205
#define IDH_DLG_IDHELP          206

#define IDH_CM_ABOUTDLG         300
#define IDH_ABOUTDLG_IDOK       301
#define IDH_ABOUTDLG_IDCANCEL   302
#define IDH_ABOUTDLG_IDHELP     303
