#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

!if !$d(MODEL)
  MODEL=f
!endif
SYSTEMS = WIN32

TARGETS = test.exe testhelp.hlp

EXERES  = test
OBJEXE  = test.obj app.obj client.obj mdidlg.obj
HLP     = testhelp
HLP_    = testhelp.hpj testhelp.rtf helpids.hh

!include $(BCEXAMPLEDIR)\owlmake.gen
