#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

DEFMODEL= f
SYSTEMS = WIN32
MYROOT  = Test
TARGETS = $(MYROOT).exe TestHelp.hlp

EXERES  = $(MYROOT)
OBJEXE  = $(MYROOT).obj app.obj client.obj mdidlg.obj
HLP     = TestHelp
HLP_    = TestHelp.hpj TestHelp.rtf helpids.hh

!include $(BCEXAMPLEDIR)\owlmake.gen
