//----------------------------------------------------------------------------
// ObjectComponents
// (C) Copyright 1994 by Borland International, All Rights Reserved
//
//   Actual BOcOle GUIDs spit out here
//----------------------------------------------------------------------------

// NOTE! This file must be compiled with the following flags for 16-bit:
//   -zE_TEXT -zFCODE    (this forces the GUIDs into the code segment)
//
#define INIT_BGUID       // force only Bolero GUIDs to be defined
#include <ocf/ocdefs.h>
#include <ocf/boleintf.h>
