#############################################################################
#
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =               \
        collate.obj  \
        _strcoll.obj \
        _strxfrm.obj \
        cconv.obj    \
        clocale.obj  \
        clower.obj   \
        ctype.obj    \
        cupper.obj   \
        is.obj       \
        lconv.obj    \
        locale.obj   \
        lsetlocl.obj \
        lstrcoll.obj \
        lstrftim.obj \
        lstrlwr.obj  \
        lstrupr.obj  \
        lstrxfrm.obj \
        ltolower.obj \
        ltoupper.obj \
        mbyte1.obj   \
        setlocal.obj \
        strcoll.obj  \
        strftime.obj \
        strlwr.obj   \
        strupr.obj   \
        strxfrm.obj  \
        tolower.obj  \
        toupper.obj  \
        _setbll.obj  \
        _setcoll.obj \
        _setudef.obj \
        _setxfrm.obj

!if $d(MT)        
    OBJS = $(OBJS)     \
           locales.obj
!endif

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

