#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\windows\dragdrop\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
CPCH    = -Hc -H"windows.h" -H=dragdrop.csm
EXERES  = dragdrop

!include $(BCEXAMPLEDIR)\makefile.gen
