#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------
EXE = gauge
MODELS=mlfd
OBJEXE = gaugex.obj
RESEXE = gaugex.res
!include $(BCEXAMPLEDIR)\owlmake.gen


