#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#
#----------------------------------------------------------------------------

MODELS=ldf
EXERES=nb
OBJEXE=nb.obj notebook.obj hscroll.obj vscroll.obj utils.obj
CCFEXE=-H

!include $(BCEXAMPLEDIR)\owlmake.gen

after: 
    del turboc.cfg
    del debug.log
    del winsight.log
