#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for List examples                                             #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l}     -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

!if $(SYSTEM)==WIN16 || $d(WIN16) || $(SYSTEM)==DOS16 || $d(DOS16) || !$d(SYSTEM)
 MODELS = mlh
!endif
SYSTEMS = DOS16 WIN16 CON32

EXE    = listx
EXEALL = listx.exe ilist.exe slist.exe islist.exe \
         dlist.exe idlist.exe sdlist.exe isdlist.exe

EXEMAKE= $(LIST) $(ILIST) $(SLIST) $(ISLIST) \
         $(DLIST) $(IDLIST) $(SDLIST) $(ISDLIST)

RULES  = myclass.obj: ..\myclass.cpp

LIST=$(EXERULE:listx.obj=listx.obj myclass.obj)
ILIST=$(LIST:listx=ilist)
SLIST=$(LIST:listx=slist)
ISLIST=$(LIST:listx=islist)
DLIST=$(LIST:listx=dlist)
IDLIST=$(LIST:listx=idlist)
SDLIST=$(LIST:listx=sdlist)
ISDLIST=$(LIST:listx=isdlist)


!include $(BCEXAMPLEDIR)\bidsmake.gen

