#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldft
EXERES = cribbage
LIBEXE = $(BCLIBDIR)\bivbx.lib
OBJEXE = cribbage.obj board.obj carddisp.obj cards.obj dialogs.obj

!include $(BCEXAMPLEDIR)\owlmake.gen

!if $(_32BIT_)
  LIBEXE=$(BCLIBDIR)\bivbx32.lib
!endif
