#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES = layout
OBJEXE = layout.obj laydia.obj
MODELS = mldf
!include $(BCEXAMPLEDIR)\owlmake.gen
