#----------------------------------------------------------------------------
# ObjectComponents
# (C) Copyright 1994 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
!if !$d(MODEL)
MODEL = s
!endif
SYSTEM = DOS16
EXE    = macrogen

!include $(BCEXAMPLEDIR)\makefile.gen
