#----------------------------------------------------------------------------
# ObjectComponents
# (C) Copyright 1994, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
!if !$d(MODEL)
MODEL = s
!endif
SYSTEM = DOS16
EXE    = macrogen

#
# should make look for BIDS somewhere other than BCROOT?
#
!if $d(BIDSINCDIR)
USERINCPATH=$(BIDSINCDIR)
!endif

!include $(BCEXAMPLEDIR)\makefile.gen
