#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES = toolbox
OBJEXE = toolboxx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen


