#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

MODELS = mldf
EXERES = mcisound
!include $(BCEXAMPLEDIR)\owlmake.gen
