#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.16  $                                                      #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =               \
	acosasin.obj \
	acossinl.obj \
	atan.obj     \
	atan2.obj    \
	atan2l.obj   \
	atanl.obj    \
	ceil.obj     \
	ceill.obj    \
	clear87.obj  \
	cos.obj      \
	cosh.obj     \
	coshl.obj    \
	cosl.obj     \
	cplx1.obj    \
	cplx2.obj    \
	crotl.obj    \
	crotr.obj    \
	ctrl87.obj   \
	cvtentry.obj \
	cvtentyw.obj \
	div.obj      \
	exp.obj      \
	expl.obj     \
	expld.obj    \
	f87atan.obj  \
	f87exp.obj   \
	f87log.obj   \
	f87sine.obj  \
	fabs.obj     \
	fabsl.obj    \
	fbstp.obj    \
	fildq.obj    \
	fistq.obj    \
	floor.obj    \
	floorl.obj   \
	fmod.obj     \
	fmodl.obj    \
	fpreset.obj  \
	frexp.obj    \
	frexpl.obj   \
	ftol.obj     \
	fuildq.obj   \
	fuistq.obj   \
	fxam.obj     \
	hypot.obj    \
	hypotl.obj   \
	i64toa.obj   \
	i64tow.obj   \
	int64toa.obj \
	int64tow.obj \
	ldexp.obj    \
	ldexpl.obj   \
	log.obj      \
	log10.obj    \
	log10l.obj   \
	logl.obj     \
	lrotl.obj    \
	lrotr.obj    \
	modf.obj     \
	modfl.obj    \
	poly.obj     \
	polyl.obj    \
	pow.obj      \
	powl.obj     \
	qdiv10.obj   \
	qmul10.obj   \
	rotl.obj     \
	rotr.obj     \
	round.obj    \
	sin.obj      \
	sinh.obj     \
	sinhl.obj    \
	sinl.obj     \
	sqrt.obj     \
	sqrtl.obj    \
	stat87.obj   \
	tan.obj      \
	tanh.obj     \
	tanhl.obj    \
	tanl.obj     \
	8087.obj     \
	abs.obj      \
	atof.obj     \
	wtof.obj     \
	atol.obj     \
	wtol.obj     \
	atoi64.obj   \
	wtoi64.obj   \
	atold.obj    \
	wtold.obj    \
	bcd1.obj     \
	cvtfak.obj   \
	cvtfakw.obj  \
	deflt87.obj  \
	efcvt.obj    \
	gcvt.obj     \
	hugeval.obj  \
	initcvt.obj  \
	labs.obj     \
	ldtrunc.obj  \
	longtoa.obj  \
	longtow.obj  \
	ltoa1.obj    \
	ltow1.obj    \
	matherr.obj  \
	matherrl.obj \
	mathptr.obj  \
	mathwhy.obj  \
	pow10d.obj   \
	pow10l.obj   \
	rand.obj     \
	realcvt.obj  \
	realcvtw.obj \
	scantod.obj  \
	scanwtod.obj \
	strtod.obj   \
	wcstod.obj   \
	strtol.obj   \
	wcstol.obj   \
	strtoul.obj  \
	wcstoul.obj  \
	xcvt.obj     \
	xcvtw.obj    \
	_ltoa1.obj   \
	_efcvt.obj   \
	_gcvt.obj    \
	_matherl.obj \
	_matherr.obj \
	_pow10.obj   \
	bcd2.obj     \
	_isnan.obj   \
	_isnanl.obj  \
	_finite.obj  \
	_finitel.obj \
	_ftoul.obj


AUXOBJS =            \
	fdiv32.obj   \
	_ll.obj

!if $d(DLL)
IMPOBJS =            \
	matherr.obj  \
	matherrl.obj \
	xinitcvt.obj
!endif

!if $d(DLL)
    IMPOBJS = $(AUXOBJS) $(IMPOBJS)
    OBJS    = $(AUXOBJS) $(OBJS)
!else
    OBJS    = $(AUXOBJS) $(OBJS)
!endif

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

cvtentyw.obj: cvtentry.asm
cvtfakw.obj : cvtfak.c
i64tow.obj  : i64toa.c
int64tow.obj: int64toa.c
longtow.obj : longtoa.c
ltow1.obj   : ltoa1.c
realcvtw.obj: realcvt.c
scanwtod.obj: scantod.c
wcstod.obj  : strtod.c
wcstol.obj  : strtol.c
wcstoul.obj : strtoul.c
wtof.obj    : atof.c
wtoi64.obj  : atoi64.c
wtol.obj    : atol.c
wtold.obj   : atold.c
xcvtw.obj   : xcvt.c
