/*
 *      C/C++ Run Time Library - Version 8.0
 *
 *      Copyright (c) 1996, 1997 by Borland International
 *      All Rights Reserved.
 *
 */
/* $Revision:   8.0  $ */

/*----------------------------------------------------------------------
 * Public variables - dummy version for RTLDLL so that linker can
 *                    resolve forced symbols
 */
int _turboFloat = 0;                    /* satisfy ext. ref. generated by BCC32 */

