#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\minihelp\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = minihelp
CPCH    = -Hc -H"windows.h" -H=minihelp.csm
HLP     = minihelp
OBJEXE  = minihelp.obj winmain.obj init.obj about.obj dispatch.obj misc.obj

!include $(BCEXAMPLEDIR)\makefile.gen
