#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldft
EXE = groupbox
OBJEXE = groupbxx.obj
!include $(BCEXAMPLEDIR)\owlmake.gen

