# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=CMNCTRLS
ROOT=..\..
OBJS=animctrl.obj   ctrldemo.obj   listcpg.obj    mlistctl.obj   mtreectl.obj   \
     notifwdw.obj   progctrl.obj   propsht.obj    slidctrl.obj   spinctrl.obj   \
     toolbar1.obj   toolbar2.obj   toolpage.obj   treecpg.obj
USES_DB=1

EXTRA_LIBS=/V4.0

!include <$(MAKEDIR)\..\include\mfc\mfcsamps.mak>
