/*[]------------------------------------------------------------[]*/
/*|                                                              |*/
/*|     iostdtr2.cpp                                             |*/
/*|                                                              |*/
/*|     Class iostream_withassign                                |*/
/*|          iostream_withassign::~iostream_withassign()         |*/
/*|                                                              |*/
/*[]------------------------------------------------------------[]*/

/*
 *      C/C++ Run Time Library - Version 6.5
 *
 *      Copyright (c) 1990, 1994 by Borland International
 *      All Rights Reserved.
 *
 */

#include <ioconfig.h>
#include <iostream.h>

iostream_withassign::~iostream_withassign() // nothing to do
{
}


