/*[]------------------------------------------------------------[]*/
/*|                                                              |*/
/*|     iostctr2.cpp                                             |*/
/*|                                                              |*/
/*|     Class iostream                                           |*/
/*|          iostream::iostream()                                |*/
/*|                                                              |*/
/*[]------------------------------------------------------------[]*/

/*
 *      C/C++ Run Time Library - Version 7.0
 *
 *      Copyright (c) 1990, 1996 by Borland International
 *      All Rights Reserved.
 *
 */

#include <ioconfig.h>
#include <iostream.h>

iostream::iostream() :
        istream(),
        ostream()
{
}


