/*[]------------------------------------------------------------[]*/
/*|                                                              |*/
/*|     istdtr2.cpp                                              |*/
/*|                                                              |*/
/*|     Class istream_withassign                                 |*/
/*|          istream_withassign::~istream_withassign()           |*/
/*|                                                              |*/
/*[]------------------------------------------------------------[]*/

/*
 *      C/C++ Run Time Library - Version 7.0
 *
 *      Copyright (c) 1990, 1996 by Borland International
 *      All Rights Reserved.
 *
 */

#include <ioconfig.h>
#include <iostream.h>

istream_withassign::~istream_withassign()
{
}


