/*[]------------------------------------------------------------[]*/
/*|                                                              |*/
/*|     ostdtr2.cpp                                              |*/
/*|                                                              |*/
/*|     Class ostream_withassign                                 |*/
/*|          ostream_withassign::~ostream_withassign()           |*/
/*|                                                              |*/
/*[]------------------------------------------------------------[]*/

/*
 *      C/C++ Run Time Library - Version 6.5
 *
 *      Copyright (c) 1990, 1994 by Borland International
 *      All Rights Reserved.
 *
 */

#include <ioconfig.h>
#include <iostream.h>

ostream_withassign::~ostream_withassign()
{
}


