/*[]------------------------------------------------------------[]*/
/*|                                                              |*/
/*|     stctr1.cpp                                               |*/
/*|                                                              |*/
/*|     Class ios                                                |*/
/*|          ios::ios()                                          |*/
/*|                                                              |*/
/*[]------------------------------------------------------------[]*/

/*
 *      C/C++ Run Time Library - Version 8.0
 *
 *      Copyright (c) 1990, 1997 by Borland International
 *      All Rights Reserved.
 *
 */
/* $Revision:   8.2  $        */

#include <ioconfig.h>
#include <iostream.h>

ios::ios()
{
    userwords = 0;
    x_delbuf = 0;
}


