#----------------------------------------------------------------------------
#  ObjectWindows
#  Copyright (c) 1991, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

SYSTEMS=WIN16 WIN32
EXERES=helloapp
!include $(BCEXAMPLEDIR)\owlmake.gen
