#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\gdiprint\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = gdiprint
CPCH    = -Hc -H"windows.h" -H=gdiprint.csm
OBJEXE  = about.obj brushdlg.obj client.obj colordlg.obj dibutil.obj\
          dispatch.obj filedlg.obj fileio.obj filenew.obj gdiprint.obj\
          infodlg.obj init.obj misc.obj palctrl.obj palette.obj\
          pendlg.obj print.obj statbar.obj toolbar.obj winmain.obj

!include $(BCEXAMPLEDIR)\makefile.gen
