#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\windows\chelp\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
CPCH    = -Hc -H"windows.h" -H=chelp.csm
EXERES  = chelp
HLP     = chelp

!include $(BCEXAMPLEDIR)\makefile.gen
