#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES = apxmdidv
RESEXE = apxmddva.res
OBJEXE = apmdmdi1.obj apmdmdic.obj apxmddad.obj apxmddev.obj apxmddva.obj \
         apxprev.obj apxprint.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
