#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1993, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXE   =owlcmd
MODELS=ldft

!include $(BCEXAMPLEDIR)\owlmake.gen

