#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for BIDS STRNGMAX example                                     #
#                                                                          #
#   Copyright (c) Borland International 1993                               #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#                                                                          #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={s|m|c|l}         for 16-bit Windows                    #
#       make MODEL={s|m|c|l} -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

!if $(SYSTEM)==WIN16 || $d(WIN16)
 MODELS = smclh
!endif
SYSTEMS = DOS16 WIN16 CON32

EXE     = strngmax  # this target used to generate rule for making an .exe

!include $(BCEXAMPLEDIR)\bidsmake.gen
