//----------------------------------------------------------------------------
// ObjectWindows
// Copyright (c) 1993, 1995 by Borland International, All Rights Reserved
//----------------------------------------------------------------------------
#define CM_TEST       201
#define IDM_COMMANDS  202

#define IDC_BISWITCH1 101
#define IDC_BISWITCH3 104
#define IDC_BISWITCH4 107
#define IDC_BISWITCH2 103
#define IDC_BIGAUGE1  102
#define IDC_BIGAUGE2  105
#define IDC_BIGAUGE3  106
#define IDC_BIGAUGE4  108
#define IDC_BIPICT1   1001
#define IDC_BIPICT2   1002
#define IDC_BIPICT3   1003
#define IDC_GROUPBOX1 1004
#define IDC_GROUPBOX2 1005
