#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\barsdi\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = barsdi
CPCH    = -Hc -H"windows.h" -H=barsdi.csm
OBJEXE  = barsdi.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          statbar.obj toolbar.obj

!include $(BCEXAMPLEDIR)\makefile.gen
