#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\input\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = input
CPCH    = -Hc -H"windows.h" -H=input.csm
OBJEXE  = input.obj winmain.obj init.obj dispatch.obj

!include $(BCEXAMPLEDIR)\makefile.gen
