#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\threads\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = threads
CPCH    = -Hc -H"windows.h" -H=threads.csm
OBJEXE  = threads.obj winmain.obj init.obj about.obj dispatch.obj misc.obj

!include $(BCEXAMPLEDIR)\makefile.gen
