#############################################################################
#
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
#############################################################################

#############################################################################
# In order to build the OBJ list for 16 bit platforms, a definition of      #
# MODEL is required.                                                        #
#############################################################################
!if ($(OS) == DOS || $(OS) == WIN16) && !$d(MODEL)
!    error MODEL is required
!endif

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =               \
        ltoa1.obj    \
        strtol.obj   \
        strtoul.obj  \
        atol.obj     \
        ldivt.obj    \

!if $(MODEL) != t
    OBJS =  $(OBJS)  \
        bcd1.obj     \
        bcd2.obj     \
        cplx1.obj    \
        cplx2.obj
!endif

AUXOBJS =            \
        crotl.obj    \
        crotr.obj    \
        f_lxmul.obj  \
        h_ldiv.obj   \
        h_llsh.obj   \
        h_lrsh.obj   \
        h_lursh.obj  \
        n_lxmul.obj  \
        labs.obj     \
        rand.obj     \
        abs.obj      \
        divt.obj     \
        longtoa.obj  \
        lrotl.obj    \
        lrotr.obj    \
        rotl.obj     \
        rotr.obj     \
        scantol.obj

!if $(MODEL) != t
    AUXOBJS = $(AUXOBJS) \
            fpstklen.obj
!endif

!if $d(DLL)
    IMPOBJS = $(AUXOBJS)
!else
    OBJS    = $(AUXOBJS) $(OBJS)
!endif

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

