#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#   examples\owl\owlapi\button\makefile
#----------------------------------------------------------------------------

EXE    = buttonx
!include $(BCEXAMPLEDIR)\owlmake.gen

