//----------------------------------------------------------------------------
// ObjectWindows
// Copyright (c) 1995, 1996 by Borland International, All Rights Reserved
//----------------------------------------------------------------------------
#if !defined(COLMNHDR_H)
#define COLMNHDR_H

#define IDM_APPMENU             0x1000

#define CM_ADDITEM              0x1001
#define CM_REMOVEITEM           0x1002
#define CM_ALLOWTRACKING        0x1100
#define CM_ALLOWITEMCHANGING    0x1101


#endif // COLMNHDR_H
