#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES = colmnhdr
OBJEXE = colmnhdx.obj

!if "$(SYSTEM)" != "WIN16"
  OSMAJOR = 4
  OSMINOR = 0
!endif

!include $(BCEXAMPLEDIR)\owlmake.gen

