#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES = colmnhdr
OBJEXE = colmnhdx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen

