#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\editsdi\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = editsdi
CPCH    = -Hc -H"windows.h" -H=editsdi.csm
OBJEXE  = editsdi.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          file.obj filedlg.obj finddlg.obj print.obj printdlg.obj search.obj

!include $(BCEXAMPLEDIR)\makefile.gen
