#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1993, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
EXERES = aclock
MODELS = ldft
RESEXE_= cuckoo1.bmp cuckoo2.bmp cuckoo3.bmp cuckoo4.bmp\
         cuckoo5.bmp cuckoo6.bmp cuckoo7.bmp cuckoo8.bmp face_bmp.bmp
!include $(BCEXAMPLEDIR)\owlmake.gen
