#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS=ldft

EXERES = editsear
OBJEXE = editseax.obj

!include $(BCEXAMPLEDIR)\owlmake.gen

