#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1994 by Borland International
#----------------------------------------------------------------------------
MODELS = ldf

EXE    = sdiole
OBJEXE = sdiole.obj sampcont.obj
RESEXE = sdiole.res sampcont.res

!include $(BCEXAMPLEDIR)\owlocfmk.gen
EXERULE = $(EXERULE) @echo Disregard previous warning about duplicate resources
