#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\gdiinput\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = gdiinput
CPCH    = -Hc -H"windows.h" -H=gdiinput.csm
OBJEXE  = gdiinput.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          brushdlg.obj client.obj pendlg.obj statbar.obj toolbar.obj

!include $(BCEXAMPLEDIR)\makefile.gen
