#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1994 by Borland International
#----------------------------------------------------------------------------
MODELS=ldf

EXERES = ttt

DLL    = tttdll
RESDLL = ttt.res


RULES = ^
tttdll.obj : ttt.cpp ^
  $(BCC) -otttdll.obj ttt.cpp

!include $(BCEXAMPLEDIR)\owlocfmk.gen

