# Borland C++ - (C) Copyright 1993 by Borland International
# Makefile for HELPEX program

EXERES = helpex
RESEXE_= helpex.dlg helpex.h help.cur
HLP    = helpex
HLP_   = helpex.rtf keys.rtf terms.rtf\
         bullet.bmp chkboff.bmp chkbon.bmp continue.bmp done.bmp
!include $(BCEXAMPLEDIR)\makefile.gen
