//----------------------------------------------------------------------------
// ObjectWindows
// (C) Copyright 1995 by Borland International, All Rights Reserved
//----------------------------------------------------------------------------
#if !defined(RICHEDAP_H)
#define RICHEDAP_H

#include <owl/editfile.rh>

// Menu Resource IDs
//
#define IDM_APPMENU            0x1000

#define CM_VIEWTOOLBAR         IDW_TOOLBAR
#define CM_VIEWSTATUSBAR       IDW_STATUSBAR
#define CM_VIEWRULER           0x1101

#define CM_INSERTOBJECT        0x1201

#define CM_FORMATFONT          0x1301
#define CM_FORMATPARAGRAPH     0x1302
#define CM_FORMATTABS          0x1303

#define CM_FORMATBOLD          0x1350
#define CM_FORMATITALIC        0x1351
#define CM_FORMATUNDERLINE     0x1352
#define CM_FORMATSTRIKEOUT     0x1353
#define CM_FORMATTEXTDATA      0x1355
#define CM_FORMATRTFDATA       0x1356

#define CM_HELPABOUT           0x2000


// Accelerator resource IDs
//
#define IDA_RICHEDIT	         0x1000


// Print Preview glyphs
//
#define APX_PPR_PREVIOUS        24500
#define APX_PPR_NEXT            24501
#define APX_PPR_ONEUP           24502
#define APX_PPR_TWOUP           24503
#define APX_PPR_CURRPAGE        24504
#define APX_PPR_DONE            24505

#endif // RICHEDAP_H

