#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\windows\vbdialog\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
CPCH    = -Hc -H"windows.h" -H=vbdialog.csm
EXERES  = vbdialog
LIBEXE  = $(BCLIBDIR)\bivbx.lib

!include $(BCEXAMPLEDIR)\makefile.gen
!if $(_32BIT_)
  LIBEXE=$(BCLIBDIR)\bivbx32.lib
!endif
