#----------------------------------------------------------------------------
# CodeGuard
# Copyright (c) 1995, 1996 Borland International Inc.  All Rights Reserved.
#   examples\codegard\winapi\makefile
#----------------------------------------------------------------------------

OSMAJOR   = 4
OSMINOR   = 0
CODEGUARD = 2
DEBUG     = 2

CCFEXE    = -Hc -H"windows.h" -H=winapi.csm

EXERES    = winapi
OBJEXE    = winapi.obj exceptcg.obj filescg.obj memcg.obj pointcg.obj
LIBEXE    = testdll.lib
CCFEXE    = -w-aus -w-sus -w-use

DLL       = testdll

!include $(BCEXAMPLEDIR)\makefile.gen
