#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\filesys\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = filesys
CPCH    = -Hc -H"windows.h" -H=filesys.csm
OBJEXE  = filesys.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          demo.obj

!include $(BCEXAMPLEDIR)\makefile.gen
