#-----------------------------------------------------------------------------
# Borland C++ - (C) Copyright 1996 by Borland International
#   examples\vdbt\animals\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32

!ifndef SYSTEM
SYSTEM = WIN32
!endif

!ifndef MODEL
MODEL = d
!endif


!if $(SYSTEM)==WIN16
MODELS = d l
USERLIBS =bivbx.lib
DEFEXE = animls16.def
!else
MODELS = d f
USERLIBS =bivbx32.lib
DEFEXE = animls32.def
!endif

EXERES = animals
OBJEXE = beastwin.obj anmlsdlc.obj
RESEXE = beastwin.res
USERLIBPATH = $(BCEXAMPLEDIR)\..\lib
!include $(BCEXAMPLEDIR)\owlmake.gen
