# ----------------------------------------------------------------------------
#  ObjectWindows
#  Copyright (c) 1991, 1996 by Borland International, All Rights Reserved
# ----------------------------------------------------------------------------
EXERES = gdidemo
MODELS = ldf
OBJEXE = gdidemo.obj arty.obj bitblt.obj fontx.obj line.obj
RESEXE_= gdidemo.rc backgrnd.bmp ship.bmp monoship.bmp
!include $(BCEXAMPLEDIR)\owlmake.gen

