#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\cliptext\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = cliptext
CPCH    = -Hc -H"windows.h" -H=cliptext.csm
OBJEXE  = cliptext.obj winmain.obj init.obj about.obj dispatch.obj misc.obj

!include $(BCEXAMPLEDIR)\makefile.gen
