//----------------------------------------------------------------------------
// ObjectWindows
// Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
//----------------------------------------------------------------------------
#if !defined(OWLBTNX_H)
#define OWLBTNX_H


#define IDD_CLIENTDLG         100
#define IDC_1                 101
#define IDC_2                 102
#define IDC_3                 103
#define IDC_ENABLEHELP        104


//
// Predefined button IDs
//

#define IDB_BORBTNII_OK         20
#define IDB_BORBTNII_OKG        21
#define IDB_BORBTNII_CANCEL     24
#define IDB_BORBTNII_CANCELG    25
#define IDB_BORBTNII_NO         28
#define IDB_BORBTNII_NOG        29
#define IDB_BORBTNII_HELP       32
#define IDB_BORBTNII_HELPG      33


#endif  //  OWLBTNX_H

