#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldf

EXERES = glyphbtn
OBJEXE = glyphbtx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
