#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES=draw
!include $(BCEXAMPLEDIR)\owlmake.gen

