#----------------------------------------------------------------------------
# ObjectWindows - (c) Copyright 1996 by Borland International
#----------------------------------------------------------------------------

TARGETS = blazer.exe blazer.hlp
SYSTEMS = WIN32   
MODELS  = fdt
EXERES  = blazer
OBJEXE  = blazer.obj client.obj about.obj propdlgs.obj
HLP     = blazer
HLP_    = blazer.hpj blazer.rtf helpids.hh
OSMAJOR = 4
OSMINOR = 0

!include $(BCEXAMPLEDIR)\owlmake.gen

