#############################################################################
#
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.1  $                                                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
MISC =                        \
        $(LIBDIR)\import.lib  \
        $(LIBDIR)\ole2w16.lib

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

#############################################################################
# MISC explicit rules.                                                      #
#############################################################################
IMPLIBS =            \
        commdlg.def  \
        ddeml.def    \
        gdi.def      \
        kernel.def   \
        keyboard.def \
        lzexpand.def \
        mmsystem.def \
        olecli.def   \
        olesvr.def   \
        penwin.def   \
        shell.def    \
        sound.def    \
        stress.def   \
        toolhelp.def \
        user.def     \
        ver.def      \
        win87em.def  \
        winmem32.def

OLE2LIBS =           \
        compobj.def  \
        ole2.def     \
        ole2conv.def \
        ole2disp.def \
        ole2nls.def  \
        storage.def  \
        typelib.def

$(LIBDIR)\import.lib : $(IMPLIBS:.def=.fst) profc.obj guid.obj
    makersp "-+!s &\n" &&|
        $?
|   > $&.rsp
    $(TLIB) $< @$&.rsp, temp.lst
    del *.rsp
    del temp.lst
    if exist $*.bak del $*.bak

$(LIBDIR)\ole2w16.lib : $(OLE2LIBS:.def=.fst)
    makersp "-+!s &\n" &&|
        $?
|   > $&.rsp
    $(TLIB) $< @$&.rsp, temp.lst
    del *.rsp
    del temp.lst
    if exist $*.bak del $*.bak

