#----------------------------------------------------------------------------
# Borland C++ (C) Copyright 1995 by Borland International
#   examples\series\writepad\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = writepad
CPCH    = -H"windows.h" -H=writepad.csm
OBJEXE  = writepad.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          file.obj filedlg.obj finddlg.obj mdichild.obj preview.obj print.obj\
          printdlg.obj rtf.obj ruler.obj search.obj statbar.obj toolbar.obj

!include $(BCEXAMPLEDIR)\makefile.gen
