# Borland C++ - (C) Copyright 1993 by Borland International
# Makefile for DDEML program(s)

EXERES = ddeclnt
EXEALL = ddeclnt.exe ddesrvr.exe
EXEMAKE= $(DDECLNT) $(DDESRVR)

DDECLNT = $(EXERULE)
DDESRVR = $(EXERULE:ddeclnt=ddesrvr)
!include $(BCEXAMPLEDIR)\makefile.gen
