#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\windows\dlldemo\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32

!if !$d(WIN16)
     SYSTEM    = WIN32
!endif

OSMAJOR = 4
OSMINOR = 0
MODEL   = d  #force use of DLLs
CPCH    = -Hc -H"windows.h" -H=dlldemo.csm
EXERES  = dlldemo
LIBEXE  = bitmap.lib
CPCHD   = -Hc -H"windows.h" -H=bitmap.csm
DLLRES  = bitmap
OBJDLL  = bitmap.obj dllshell.obj

!include $(BCEXAMPLEDIR)\makefile.gen

