/*------------------------------------------------------------------------
 * filename - user.h
 *
 *-----------------------------------------------------------------------*/

/*
 *      C/C++ Run Time Library - Version 1.5
 *
 *      Copyright (c) 1990, 1994 by Borland International
 *      All Rights Reserved.
 *
 */

union ios_user_union {
    long lword;
    void *pword;
};

