#-----------------------------------------------------------------------------
# ObjectWindows
# (C) Copyright 1995 by Borland International
#-----------------------------------------------------------------------------

EXERES  = rolldlgx

!include $(BCEXAMPLEDIR)\owlmake.gen


