#----------------------------------------------------------------------------
# Borland C++ - (C) Copyright 1996 by Borland International
#   examples\vdbt\owlrange\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32

!ifndef SYSTEM
SYSTEM = WIN32
!endif

!ifndef MODEL
MODEL = d
!endif

!if $(SYSTEM)==WIN16

MODELS = d l
!if $(MODEL)==d
USERLIBS = bidsi.lib bdto.lib bdtc.lib ole2w16.lib
!else
USERLIBS = bidsl.lib bdto.lib bdtc.lib ole2w16.lib
!endif
SUFFIX   = 16

!else

#WIN32 Macro definitions
MODELS = d f

!if $(MODEL)==d
USERLIBS = bidsfi.lib bdtof.lib bdtcf.lib ole2w32.lib
!else
USERLIBS = bidsf.lib bdtof.lib bdtcf.lib ole2w32.lib
!endif

SUFFIX   = 32
!endif

APPNAME = owlrange
EXERES  = $(APPNAME)
OBJEXE  = $(APPNAME).obj print.obj
RESEXE  = $(APPNAME).res
RESEXE_ = $(APPNAME).ico

USERLIBPATH = $(BCEXAMPLEDIR)\..\lib

!include $(BCEXAMPLEDIR)\makefile.gen

CFLAGS = $(CFLAGS) -DSTRICT

