#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES = apxmdi
RESEXE = apxmdapp.res
OBJEXE = apxmdabd.obj apxmdapp.obj apxmdedf.obj apxmmdi1.obj apxmmdic.obj \
         apxprev.obj apxprint.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
