#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1995 by Borland International
#----------------------------------------------------------------------------

MODELS=lfd
EXERES=drawedge
!include $(BCEXAMPLEDIR)\owlmake.gen


