//----------------------------------------------------------------------------
// ObjectComponents
// Copyright (c) 1994, 1997 by Borland International, All Rights Reserved
//
// $Revision:   2.14  $
//----------------------------------------------------------------------------
#if defined(__TRACE) || defined(__WARN)
# pragma message ocf/boleintf.h has been replaced by ocf/ocbocole.h
#endif
#include <ocf/ocbocole.h>
