//----------------------------------------------------------------------------
// ObjectComponents
// Copyright (c) 1994, 1997 by Borland International, All Rights Reserved
//
// $Revision:   2.6  $
//----------------------------------------------------------------------------
#if defined(__TRACE) || defined(__WARN)
# pragma message ocf/ocdefs.h has been replaced by ocf/defs.h & ocf/oleutil.h
#endif
#if !defined(OCF_DEFS_H)
# include <ocf/defs.h>
#endif
#if !defined(OCF_OLEUTIL_H)
# include <ocf/oleutil.h>
#endif
