//----------------------------------------------------------------------------
// ObjectComponents
// Copyright (c) 1994, 1996 by Borland International, All Rights Reserved
//
// Include for OC, gets common headers when precompiled headers are enabled.
//----------------------------------------------------------------------------
#if !defined(OCF_PCH_H)
#define OCF_PCH_H

#if defined(_OCFPCH)
# include <ocf/defs.h>
# include <ocf/oleutil.h>
# include <ocf/autodefs.h>
# include <ocf/automacr.h>
# include <ocf/ocobject.h>
# include <ocf/ocstorag.h>
# include <ocf/ocreg.h>
# include <ocf/ocapp.h>
# include <ocf/ocdoc.h>
# include <ocf/ocpart.h>
# include <ocf/ocview.h>
# include <ocf/ocremvie.h>
#endif

#endif
