#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\analog\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
CPCH    = -Hc -H"windows.h" -H=analog.csm
EXERES  = analog
OBJEXE  = analog.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          copier.obj

!include $(BCEXAMPLEDIR)\makefile.gen
