//----------------------------------------------------------------------------
// ObjectWindows - (C) Copyright 1991, 1993 by Borland International
//   Resource IDs for predefined OWL resources
//----------------------------------------------------------------------------

//
// Commands are defined in standard Owl 2 headers
//

//
// String IDs
//
#define SR_CANNOTFIND       32540     // located in editstr.rc
#define SR_UNTITLED         32550     // located in filestr.rc
#define SR_UNABLEREAD       32551
#define SR_UNABLEWRITE      32552
#define SR_FILECHANGED      32553
#define SR_FILEFILTER       32554

//
// Dialog and controls IDs
//
#define SD_FILEOPEN         32512     // located in filedial.dlg
#define SD_FILESAVE         32513
#define ID_FNAME            4095
#define ID_FPATH            4094
#define ID_FLIST            4093
#define ID_DLIST            4092

#define SD_INPUTDIALOG      32514     // located in inputdia.dlg
#define ID_PROMPT           4091
#define ID_INPUT            4090

#define ID_TITLE  101                 // located in printer.rc
#define ID_DEVICE 102
#define ID_PORT   103

#define SD_SEARCH           32528     // located in stdwnd.dlg
#define SD_REPLACE          32529
#define ID_SEARCHTEXT       4089
#define ID_CASESENSITIVE    4088
#define ID_REPLACETEXT      4087
#define ID_REPLACEALL       4086
#define ID_PROMPTONREPLACE  4085

#define ID_EDITOR           4084
