# Borland C++ - (C) Copyright 1993 by Borland International
# Makefile for tdwdemo program -
#   This example has two versions: buggy (tdwdemo.bug) and clean (s_paint.c).
#   To make the example using this makefile, copy one of these files to
#   the source file TDWDEMO.C

SYSTEMS= WIN16 WIN32
EXERES = tdwdemo
!include $(BCEXAMPLEDIR)\makefile.gen


