#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES = notify
MODELS = ldft

!include $(BCEXAMPLEDIR)\owlmake.gen
