#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS  = dft
SYSTEMS = WIN32

EXERES = listwind
OBJEXE = listwinx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
