#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

!if !$d(MODEL)
  MODEL=l
!endif

EXERES   = simbor
OBJEXE   = app.obj simbor.obj bordlg.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
