#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

DEFMODEL = l
MYROOT   = SimBor

EXERES   = $(MYROOT)
OBJEXE   = app.obj $(MYROOT).obj bordlg.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
