#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.15  $                                                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =               \
        access.obj   \
        allocbuf.obj \
        cfinfo.obj   \
        chsize.obj   \
        clearerr.obj \
        close.obj    \
        closeall.obj \
        creat.obj    \
        createmp.obj \
        creatnew.obj \
        dup.obj      \
        dup2.obj     \
        eof.obj      \
        fclose.obj   \
        fdopen.obj   \
        fflush.obj   \
        fgetchar.obj \
        fgetpos.obj  \
        fgets.obj    \
        fgetwchr.obj \
        fgetws.obj   \
        files.obj    \
        files2.obj   \
        findfrst.obj \
        flushall.obj \
        flushout.obj \
        fmode.obj    \
        fmodeptr.obj \
        fnmerge.obj  \
        fnsplit.obj  \
        fopen.obj    \
        fprintf.obj  \
        fprintfw.obj \
        fputchar.obj \
        fputn.obj    \
        fputnw.obj   \
        fputs.obj    \
        fputwchr.obj \
        fputws.obj   \
        fread.obj    \
        freopen.obj  \
        fscanf.obj   \
        fscanfw.obj  \
        fseek.obj    \
        fsetpos.obj  \
        ftruncat.obj \
        fwrite.obj   \
        getcwd.obj   \
        getftime.obj \
        gets.obj     \
        getw.obj     \
        getws.obj    \
        iomacro.obj  \
        isatty.obj   \
        lgetc.obj    \
        lgetwc.obj   \
        lputc.obj    \
        lputwc.obj   \
        lseek.obj    \
        makepath.obj \
        mkname.obj   \
        mktemp.obj   \
        open.obj     \
        perror.obj   \
        printf.obj   \
        printfw.obj  \
        puts.obj     \
        putw.obj     \
        putws.obj    \
        read.obj     \
        remove.obj   \
        rewind.obj   \
        rmtmp.obj    \
        scanf.obj    \
        scanfw.obj   \
        scanner.obj  \
        scannerw.obj \
        scantol.obj  \
        scanwtol.obj \
        scn2i64.obj  \
        scn2i64w.obj \
        setbuf.obj   \
        setftime.obj \
        setmode.obj  \
        setvbuf.obj  \
        sopen.obj    \
        splitpth.obj \
        sprintf.obj  \
        sprintfw.obj \
        sscanf.obj   \
        sscanfw.obj  \
        streams.obj  \
        tell.obj     \
        tempnam.obj  \
        tmpfile.obj  \
        tmpnam.obj   \
        umask.obj    \
        ungetc.obj   \
        ungetwc.obj  \
        vfprintf.obj \
        vfprntfw.obj \
        vfscanf.obj  \
        vfscanfw.obj \
        vprinter.obj \
        vprintf.obj  \
        vprintfw.obj \
        vprintrw.obj \
        vscanf.obj   \
        vscanfw.obj  \
        wcreat.obj   \
        wfndfrst.obj \
        wfopen.obj   \
        wfreopen.obj \
        wgetcwd.obj  \
        wiomacro.obj \
        wmakepth.obj \
        wmkname.obj  \
        wmktemp.obj  \
        wperror.obj  \
        write.obj    \
        wsopen.obj   \
        wspltpth.obj \
        wfnmerge.obj \
        wtempnam.obj \
        wtmpnam.obj  \
        xfclose.obj  \
        xfflush.obj  \
        _getw.obj    \
        _putw.obj    \
        __eof.obj    \
        __read.obj   \
        __wread.obj  \
        __write.obj  \
        _cfinfo.obj  \
        _creat.obj   \
        _mktemp.obj  \
        _rmtmp.obj   \
        _fdopen.obj  \
        _flshall.obj \
        _fputc.obj   \
        _unlink.obj  \
        _tempnam.obj \
        _fputwc.obj  \
        _fsopen.obj  \
        _popen.obj   \
        _umask.obj   \
        _fputchr.obj \
        _fgetchr.obj \
        _fileno.obj  \
        _fclosal.obj \
        _sopen.obj   \
	_wcreat.obj  \
        _wfdopen.obj \
        _wfsopen.obj \
        _wpopen.obj




!if $d(MT)
    OBJS = $(OBJS)       \
           fgetc.obj    \
           fgetwc.obj   \
           fputc.obj    \
           fputwc.obj
!endif

!if $d(DLL)
    IMPOBJS = fmode.obj
!else
    MISC    = $(LIBDIR)\fileinfo.obj
!endif

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

#############################################################################
# MISC explicit rules.                                                      #
#############################################################################
$(LIBDIR)\fileinfo.obj : fileinfo.obj
    copy $** $(LIBDIR)\$.

# Special rules for wide-char versions so that they depend on the dual-mode
# source code in the non-w files

fgetwc.obj   : fgetc.c
fgetwchr.obj : fgetchar.c
fgetws.obj   : fgets.c
fprintfw.obj : fprintf.c
fputnw.obj   : fputn.c
fputwc.obj   : fputc.c
fputwchr.obj : fputchar.c
fputws.obj   : fputs.c
fscanfw.obj  : fscanf.c
getws.obj    : gets.c
lgetwc.obj   : lgetc.c
lputwc.obj   : lputc.c
printfw.obj  : printf.c
putws.obj    : puts.c
scanfw.obj   : scanf.c
scannerw.obj : scanner.c
scanwtol.obj : scantol.c
sprintfw.obj : sprintf.c
sscanfw.obj  : sscanf.c
ungetwc.obj  : ungetc.c
vfprntfw.obj : vfprintf.c
vfscanfw.obj : vfscanf.c
vprintfw.obj : vprintf.c
vprintrw.obj : vprinter.c
vscanfw.obj  : vscanf.c
wcreat.obj   : creat.c
wfndfrst.obj : findfrst.c
wfopen.obj   : fopen.c
wfreopen.obj : freopen.c
wgetcwd.obj  : getcwd.c
wiomacro.obj : iomacro.c
wmakepth.obj : makepath.c
wmkname.obj  : mkname.c
wmktemp.obj  : mktemp.c
wperror.obj  : perror.c
wspltpth.obj : splitpth.c
wfnmerge.obj : fnmerge.c
wtempnam.obj : tempnam.c
wtmpnam.obj  : tmpnam.c
__wread.obj  : __read.c
_wcreat.obj  : _creat.c
_wfdopen.obj : _fdopen.c
_wfsopen.obj : _fsopen.c
_wpopen.obj  : _popen.c
