#----------------------------------------------------------------------------
# CodeGuard
# Copyright (c) 1995, 1996 Borland International Inc.  All Rights Reserved.
#   examples\codegard\lang\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 CON32

!if !$d(WIN16)
     SYSTEM    = CON32
     CODEGUARD = 2
!else
     MODEL     = l
     CODEGUARD = 1
!endif

OSMAJOR = 4
OSMINOR = 0
DEBUG   = 1

EXE     = sampexe
EXEALL  = lang.exe gpfault.exe zerodiv.exe
EXEMAKE = $(LANG) $(GPFAULT) $(ZERODIV)

LANG    = $(EXERULE:sampexe=lang)
GPFAULT = $(EXERULE:sampexe=gpfault)
ZERODIV = $(EXERULE:sampexe=zerodiv)

CCFEXE  = -w-use -w-aus -w-sus -w-par

!include $(BCEXAMPLEDIR)\makefile.gen

