#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES=sdifile
MODELS=ldf
!include $(BCEXAMPLEDIR)\owlmake.gen

