#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\tabctrl\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
CPCH    = -Hc -H"windows.h" -H=tabctrl.csm
EXERES  = tabctrl
OBJEXE  = tabctrl.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          demo.obj

!include $(BCEXAMPLEDIR)\makefile.gen
