#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldft

EXERES = docking
OBJEXE = dockingx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
