#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\win95\dropext\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
DLL     = dropext
OBJDLL  = dropext.obj defclsf.obj
DEFDLL  = dropext.def
LIBDLL  = $(BCLIBDIR)\ole2w32.lib
CPCH    = -Hc -H"windows.h" -H=dropext.csm

!include $(BCEXAMPLEDIR)\makefile.gen

