#############################################################################
#
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
!if $(OS) == DPMI16
    OBJS =               \
        bioskey.obj  \
        bios_key.obj \
        bioscom.obj  \
        bios_com.obj \
        biosprin.obj \
        bios_prn.obj

!else

    AUXOBJS =        \
        biosequ.obj  \
        bios_equ.obj

!   if $d(DLL)
        IMPOBJS = $(AUXOBJS)
!   else
        OBJS    = $(AUXOBJS)
!   endif

!endif

!if $(OS) == DOS
    OBJS =  $(OBJS)      \
            bioscom.obj  \
            biosdisk.obj \
            bioskey.obj  \
            biosprin.obj \
            bios_com.obj \
            bios_dsk.obj \
            bios_key.obj \
            bios_prn.obj
!endif

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

