#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\barmdi\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = barmdi
CPCH    = -Hc -H"windows.h" -H=barmdi.csm
OBJEXE  = barmdi.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          mdichild.obj statbar.obj toolbar.obj

!include $(BCEXAMPLEDIR)\makefile.gen
