#----------------------------------------------------------------------------
# Borland C++ (C) Copyright 1995 by Borland International
#   examples\series\menu\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
EXERES  = menu
CPCH    = -H"windows.h" -H=menu.csm
OSMAJOR = 4
OSMINOR = 0
OBJEXE  = menu.obj winmain.obj init.obj dispatch.obj ownrdraw.obj popup.obj

!include $(BCEXAMPLEDIR)\makefile.gen
