#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\windows\dbugdemo\makefile
#----------------------------------------------------------------------------

# This example is designed to be used in conjunction with the tutorial
# contained in Chapter 4 of the Turbo Debugger User's Guide, "Debugging
# a simple example."  The project will not build without following the
# directions contained in the tutorial.

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
DEBUG   = 1
CPCH    = -Hc -H"windows.h" -H=dbugdemo.csm
EXERES  = dbugdemo

!include $(BCEXAMPLEDIR)\makefile.gen


