#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXE   =scrollex
MODELS=mldf
!include $(BCEXAMPLEDIR)\owlmake.gen

