#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXE   =scroller
OBJEXE = scrollex.obj
MODELS=mldf
!include $(BCEXAMPLEDIR)\owlmake.gen

