#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.2  $                                                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
!if $(OS) == DOS
    OBJS =               \
            exec.obj     \
            setargv.obj  \
            setenvp.obj  \
            signal.obj   \
            int86.obj    \
            intdos.obj   \
            intr.obj     \
            setjmp.obj   \
            wild.obj

!   if $(MODEL) != t
        MISC =               \
                setjmpnx.obj
!   endif

!   if $(MODEL) == c
        MISC = $(MISC)                \
               $(LIBDIR)\wildargs.obj
!   endif
!endif

OBJS =  $(OBJS)      \
        delay.obj    \
        doscmd.obj   \
        execl.obj    \
        execle.obj   \
        execlp.obj   \
        execlpe.obj  \
        execv.obj    \
        execve.obj   \
        execvp.obj   \
        execvpe.obj  \
        loadprog.obj \
        sleep.obj    \
        spawn.obj    \
        spawnl.obj   \
        spawnle.obj  \
        spawnlp.obj  \
        spawnlpe.obj \
        spawnv.obj   \
        spawnve.obj  \
        spawnvp.obj  \
        spawnvpe.obj \
        system.obj

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

#############################################################################
# MISC explicit rules.                                                      #
#############################################################################
setjmpnx.obj : setjmp.cas
    $(CC) -o$(OBJDIR)\$& -DNOXX $?

$(LIBDIR)\wildargs.obj : wildargs.obj
    copy $** $(LIBDIR)\$.

