#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#   examples\owl\owlapi\groupbox\makefile
#----------------------------------------------------------------------------

MODELS = mldf
EXE = groupbox
OBJEXE = groupbxx.obj
!include $(BCEXAMPLEDIR)\owlmake.gen

