#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#   examples\owl\owlapi\groupbox\makefile
#----------------------------------------------------------------------------

EXE = groupbxx
!include $(BCEXAMPLEDIR)\owlmake.gen

