#----------------------------------------------------------------------------
# Borland C++ (C) Copyright 1995 by Borland International
#   examples\series\rtfedit\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN32
OSMAJOR = 4
OSMINOR = 0
CPCH    = -H"windows.h" -H=rtfedit.csm
EXERES  = rtfedit
OBJEXE  = rtfedit.obj winmain.obj init.obj about.obj dispatch.obj misc.obj

!include $(BCEXAMPLEDIR)\makefile.gen
