#define IDS_APPNAME                     1
#define IDS_DESCRIPTION                 2
#define IDD_VERFIRST                    100
#define IDI_APPICON                     101
#define IDD_VERLAST                     104
#define IDM_EXIT                        1000
#define IDM_ABOUT                       1100
#define IDM_BOLD                        1200
#define IDM_ITALIC                      1201
#define IDM_UNDERLINE                   1202
#define IDM_FONTS                       1203

