#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES = sysinfo
!include $(BCEXAMPLEDIR)\owlmake.gen
