//----------------------------------------------------------------------------
// ObjectWindows - (C) Copyright 1991, 1993 by Borland International
//----------------------------------------------------------------------------

//
//
//
//
// 16 bit ids
//
#define IDS_ENHANCED     0
#define IDS_STANDARD     1
#define IDS_REAL         2
#define IDS_CPU8086      3
#define IDS_CPU80186     4
#define IDS_CPU80286     5
#define IDS_CPU80386     6
#define IDS_CPU80486     7
#define IDS_YES          8
#define IDS_NO           9
#define IDS_UNKNOWN      10

#define IDC_INSTANCENUMBER       200
#define IDC_WINDOWSVERSION       201
#define IDC_OPERATIONMODE        202
#define IDC_CPUTYPE              203
#define IDC_COPROCESSOR          204
#define IDC_GLOBAL               205
#define IDC_VERSIONDOS           206

//
// 32 bit ids
//
//#define IDC_WINDOWSVERSION     301 // same as 16bit
#define IDC_OEMID                300
#define IDC_PAGESIZE             301
#define IDC_MINAPPADDRESS        302
#define IDC_MAXAPPADDRESS        303
#define IDC_ACTIVEPROMASK        304
#define IDC_NUMPROS              305
#define IDC_PROTYPE              306
#define IDC_ALLOCGRAN            307
#define IDC_RESERVED             308
