#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES=paint
MODELS=ldf
OBJEXE=paint.obj dibattr.obj
!include $(BCEXAMPLEDIR)\owlmake.gen

