#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for Set examples                                              #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l}     -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

!if $(SYSTEM)==WIN16 || $d(WIN16) || $(SYSTEM)==DOS16 || $d(DOS16) || !$d(SYSTEM)
 MODELS = mlh
!endif
SYSTEMS = DOS16 WIN16 CON32

EXE    = setx
EXEALL = setx.exe iset.exe

EXEMAKE= $(SET) $(ISET)

RULES  = myclass.obj: ..\myclass.cpp

SET=$(EXERULE:setx.obj=setx.obj myclass.obj)
ISET=$(SET:setx=iset)


!include $(BCEXAMPLEDIR)\bidsmake.gen

