#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ftd
OBJEXE = mciwnd.obj mciwndx.obj
EXERES = mciwndx

!include $(BCEXAMPLEDIR)\owlmake.gen
