#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
SYSTEM = WIN32
MODELS = ftd
OBJEXE = mciwnd.obj mciwndx.obj
EXERES = mciwndx

!include $(BCEXAMPLEDIR)\owlmake.gen
