//----------------------------------------------------------------------------
// ObjectWindows
// Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
//
//  Sample illustrating TMCIWnd class
//----------------------------------------------------------------------------
#if !defined(MCIWNDX_H)
#define MCIWNDX_H

#define IDD_MCIWNDDLG         0x5000
#define IDC_MCIWNDCTL         0x1000

#define IDM_APP               0x1000
#define CM_MCIWND             0x1001

#endif // MCIWNDX_H

