#----------------------------------------------------------------------------
# ObjectComponents
# (C) Copyright 1994 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
MODEL = l
SYSTEM = WIN16
EXERES = autogen
DOSSTUB= wrw.stb

!include $(BCEXAMPLEDIR)\ocfmake.gen
