#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldft

EXE    = splash
OBJEXE = splashx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
