#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.6  $                                                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =               \
        setjmp.obj   \
        loadprog.obj \
        wloadprg.obj \
        setenv.obj   \
        wsetenv.obj  \
        setenvp.obj  \
        wsetenvp.obj \
        signal.obj   \
        sleep.obj    \
        system.obj   \
        wsystem.obj  \
        _cwait.obj   \
        _getpid.obj

!if $d(DLL)
IMPOBJS =            \
	xsetenvp.obj \
	wxsetenp.obj
!endif

!if !$d(DLL)
MISC    = setjmpnx.obj
!endif

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

#############################################################################
# MISC explicit rules.                                                      #
#############################################################################
setjmpnx.obj : setjmp.asm
    $(ASM) -DNOXX $?, $(OBJDIR)\$&

wsetenv.obj : setenv.c
wsetenvp.obj : setenvp.c
wloadprg.obj : loadprog.c
wsystem.obj : system.c

