#-----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1994 by Borland International
#   Regtest application -- makefile.
#
#-----------------------------------------------------------------------------

MODELS = ldf

EXERES = regtest

!include $(BCEXAMPLEDIR)\ocfmake.gen










