#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for Deque examples                                            #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l}     -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

!if $(SYSTEM)==WIN16 || $d(WIN16) || $(SYSTEM)==DOS16 || $d(DOS16) || !$d(SYSTEM)
 MODELS = mlh
!endif
SYSTEMS = DOS16 WIN16 CON32

EXE    = deque
EXEALL = deque.exe ideque.exe deqlist.exe ideqlist.exe

EXEMAKE= $(DEQUE) $(IDEQUE) $(DEQLIST) $(IDEQLIST)

RULES  = myclass.obj: ..\myclass.cpp

DEQUE=$(EXERULE:deque.obj=deque.obj myclass.obj)
IDEQUE=$(DEQUE:deque=ideque)
DEQLIST=$(DEQUE:deque=deqlist)
IDEQLIST=$(DEQUE:deque=ideqlist)


!include $(BCEXAMPLEDIR)\bidsmake.gen

