#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1994 by Borland International
#----------------------------------------------------------------------------

MODELS=ldf

EXERES = LOCALIZE
!include $(BCEXAMPLEDIR)\ocfmake.gen
