#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXE = palette
OBJEXE = palettex.obj
RESEXE = palettex.res
MODELS=mldf
!include $(BCEXAMPLEDIR)\owlmake.gen

