#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for DATE example                                              #
#                                                                          #
#   Copyright (c) 1994 Borland International                               #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#                                                                          #
#       make -DCON32                    for 32-bit Windows Console         #
#       make MODEL={s|m|c|l}            for 16-bit Windows using EasyWin   #
#       make MODEL={s|m|c|l|h} -DDOS16  for 16-bit DOS                     #
#                                                                          #
#--------------------------------------------------------------------------#

EXE    = datex

!include $(BCEXAMPLEDIR)\bidsmake.gen

