#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES = metafile
OBJEXE = metafilx.obj
!include $(BCEXAMPLEDIR)\owlmake.gen

