//----------------------------------------------------------------------------
// ObjectWindows
// (C) Copyright 1995 by Borland International, All Rights Reserved
//----------------------------------------------------------------------------
#if !defined(TOOLTIPX_H)
#define TOOLTIPX_H

#include <owl/window.rh>
#include <owl/editfile.rh>

#define ID_REDTOOL    0x1000
#define ID_BLUETOOL   0x1001
#define ID_YELLOWTOOL 0x1002
#define ID_GREENTOOL  0x1003
#define IDM_MAINMENU  100

#define CM_TOOLBARTIP 0x2001
#define CM_WINDOWTIP  0x2002


#endif // TOOLTIPX_H

