#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1992, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = ldft
EXERES = led
OBJEXE = led.obj ledwind.obj
!include $(BCEXAMPLEDIR)\owlmake.gen
