//----------------------------------------------------------------------------
// ObjectWindows
// (C) Copyright 1991, 1994 by Borland International, All Rights Reserved
//
//  Default OwlMain to satisfy LibMain in DLLs that aren't components
//----------------------------------------------------------------------------
#include <owl/owlpch.h>

int
OwlMain(int /*argc*/, char* /*argv*/ [])
{
  return 0;
}
