/////////////////////////////////////////////////////////////////////////////////
// CORBAPCH.H - Borland C++Builder CORBA pre-compiled header file
// $Revision:   1.2  $
// Copyright (c) 1998, 1999 Inprise Corporation
/////////////////////////////////////////////////////////////////////////////////
#ifndef CORBAPCH_H
#define CORBAPCH_H

#include <sys/types.h>
#include <string.h>
#include <stdlib.h>
#include <vdef.h>
#include <vpre.h>
#include <viostrm.h>  
#include <vtypeinf.h>
#include <vpost.h>

#endif // CORBAPCH_H
