#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXE   =static
OBJEXE = staticx.obj
MODELS=mldf
!include $(BCEXAMPLEDIR)\owlmake.gen

