#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES = checklst
OBJEXE = checklsx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen


