#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for BAG examples                                              #
#                                                                          #
#   Copyright (c) 1994 Borland International                               #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#                                                                          #
#       make -DCON32                    for 32-bit Windows Console         #
#       make MODEL={s|m|c|l}            for 16-bit Windows using EasyWin   #
#       make MODEL={s|m|c|l|h} -DDOS16  for 16-bit DOS                     #
#                                                                          #
#--------------------------------------------------------------------------#

EXE    = bag
EXEALL = bag.exe ibag.exe

EXEMAKE= $(BAG) $(IBAG)

RULES  = myclass.obj: ..\myclass.cpp

BAG=$(EXERULE:bag.obj=bag.obj myclass.obj)
IBAG=$(BAG:bag=ibag)


!include $(BCEXAMPLEDIR)\bidsmake.gen

