#############################################################################
#
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
OBJS =              \
        libmain.obj

!if $d(DLL)
    IMPOBJS =           \
            libmain.obj

    MISC =                      \
            $(LIBDIR)\c0d32.obj

!elif !$d(MT)
    MISC =                      \
            $(LIBDIR)\c0w32.obj \
            $(LIBDIR)\c0x32.obj
!endif

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

#############################################################################
# MISC explicit rules.                                                      #
#############################################################################
$(LIBDIR)\c0x32.obj : c0nt.obj
    copy $** $<

$(LIBDIR)\c0w32.obj : c0ntw.obj
    copy $** $<

$(LIBDIR)\c0d32.obj : c0ntd.obj
    copy $** $<

c0ntw.obj : c0nt.asm

c0ntd.obj : c0nt.asm

