//----------------------------------------------------------------------------
// ObjectWindows - (C) Copyright 1991, 1993 by Borland International
//----------------------------------------------------------------------------

#define IDI_MULTIFILE       101
#define IDI_DOC             102

#define CM_TOGGLEHINT       202
#define CM_TOGGLEBAR        203

#define IDA_MDIFILE         100

#define IDM_EDITFILE_DOC    100
#define IDM_EDITFILE_CHILD  101

#define IDW_STATUSBAR       32000   // Copied from include\owl\messageb.h
#define IDW_TOOLBAR         1000    // Assigned to toolbar in BuildControlBar()
