#----------------------------------------------------------------------------
# Borland C++
# Copyright (c) 1987, 1996 Borland International Inc.  All Rights Reserved.
#   examples\series\simple\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = simple
CPCH    = -Hc -H"windows.h" -H=simple.csm
OBJEXE  = simple.obj winmain.obj init.obj

!include $(BCEXAMPLEDIR)\makefile.gen
