#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES = apxdlgdv
RESEXE = apxdlgda.res
OBJEXE = apxdlddc.obj apxdlgda.obj

!include $(BCEXAMPLEDIR)\owlmake.gen
