#############################################################################
#                                                                           #
# The make process relies on the creation of DLL and library response file  #
# creation.  To control the location of object modules the following should #
# be defined:                                                               #
#                                                                           #
#     IMPOBJS - A list of object modules that should appear in the DLL      #
#               import library.                                             #
#                                                                           #
#        OBJS - If a DLL is build, this is a list of the object modules     #
#               that are linked into the DLL.  If building a library, this  #
#               is the list of object modules that goes into the library.   #
#                                                                           #
# The building of miscellaneous object modules and libraries is controlled  #
# by the list of files in the MISC variable.                                #
#                                                                           #
# $Revision:   8.2  $                                                                #
#                                                                           #
#############################################################################

#############################################################################
# Build the object module lists.                                            #
#############################################################################
!if $(OS) == DOS || $(OS) == DPMI16
    OBJS =               \
            cgets.obj    \
            clreol.obj   \
            clrscr.obj   \
            color.obj    \
            cprintf.obj  \
            cputs.obj    \
            cscanf.obj   \
            cursor.obj   \
            getpass.obj  \
            gotoxy.obj   \
            gptext.obj   \
            insline.obj  \
            movetext.obj \
            putch.obj    \
            screen.obj   \
            scroll.obj   \
            textmode.obj \
            vidinfo.obj  \
            wherexy.obj  \
            window.obj   \
            crtinit.obj  \
            getch.obj    \
            kbhit.obj
!endif

!if $(OS) == DPMI16
    OBJS =  $(OBJS)      \
            wscroll.obj
!else
    OBJS =  $(OBJS)      \
            direct.obj

    AUXOBJS =            \
            wscroll.obj  \
            vram.obj

!   if $d(DLL)
        IMPOBJS = $(AUXOBJS)
!   else
        OBJS    = $(AUXOBJS) $(OBJS)
!   endif
!endif

#############################################################################
# Configure the environment appropriately.                                  #
#############################################################################
TASMCFG = 1        # Force tasm.cfg creation

!include rules.mak

