#--------------------------------------------------------------------------#
#                                                                          #
#   MAKEFILE for Persistent Stream examples                                #
#                                                                          #
#   Copyright (c) 1994, 1996 Borland International                         #
#   All Rights Reserved                                                    #
#                                                                          #
#   Usage:                                                                 #
#       make MODEL=f                 for 32-bit Windows                    #
#       make MODEL={m|l}             for 16-bit Windows                    #
#       make MODEL={m|l}     -DDOS16 for 16-bit DOS                        #
#                                                                          #
#--------------------------------------------------------------------------#

MODELS  = mlft
SYSTEMS = DOS16 WIN16 CON32
EXE    = stream0
EXEALL = stream0.exe stream1.exe stream2.exe stream3.exe

EXEMAKE= $(STREAM0) $(STREAM1) $(STREAM2) $(STREAM3)

STREAM0=$(EXERULE:stream0.obj=stream0.obj strmpnt.obj)
STREAM1=$(STREAM0:stream0=stream1)
STREAM2=$(STREAM0:stream0=stream2)
STREAM3=$(STREAM0:stream0=stream3)

!include $(BCEXAMPLEDIR)\bidsmake.gen

