#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES=owlscrn
EXEBIN=$(EXERES).scr
OBJEXE=tscrnsav.obj owlscrn.obj
DEFEXE=owlscrn.def
MODELS=mldf
!include $(BCEXAMPLEDIR)\owlmake.gen
