//----------------------------------------------------------------------------
// ObjectWindows - (C) Copyright 1991, 1993 by Borland International
//----------------------------------------------------------------------------

#define ID_DOTS	  111
#define ID_LINES  112
#define ID_BLOBS	113

#define ID_SLOW   121
#define ID_MED    122
#define ID_FAST   123
#define IDC_GROUPBOX1	114
#define IDC_GROUPBOX2	115

