#----------------------------------------------------------------------------
# Borland C++ - (C) Copyright 1996 by Borland International
#   examples\vdbt\query\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32

!if $(SYSTEM)==WIN16
SUFFIX   = 16
USERLIBS = bdtci.lib mathwl cwl
!else
SUFFIX   = 32
USERLIBS = bdtcfi.lib
!endif

APPNAME = query
DEFEXE  = $(APPNAME)$(SUFFIX).def
EXERES  = $(APPNAME)
OBJEXE  = $(APPNAME).obj
RESEXE  = $(APPNAME).res
RESEXE_ = $(APPNAME).ico

USERLIBPATH = $(BCEXAMPLEDIR)\..\lib

!include $(BCEXAMPLEDIR)\makefile.gen

CFLAGS = $(CFLAGS) -DSTRICT
