#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------
EXERES=owlscrn
EXEBIN=$(EXERES).scr
OBJEXE=tscrnsav.obj owlscrn.obj
MODELS=ldf
!include $(BCEXAMPLEDIR)\owlmake.gen
