:// -------------------------------------------------------------------------
:// ObjectComponents
:// Copyright (c) 1991, 1996 by Borland International, All Rights Reserved
://
:// $Revision:   2.1  $
:// $Author:   BBABET  $
:// $Date:   18 Dec 1995 12:52:20  $
:// -------------------------------------------------------------------------

copy bole16.rc bocole.rc
copy bole16.def bocole.def
copy bole32.rc bocolef.rc
copy bole32.def bocolef.def
