#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1996 by Borland International, All Rights Reserved
#
# $Revision:   10.11  $
#----------------------------------------------------------------------------
EXE    = ocxdlg
RESEXE = ocxdlgap.res
DEFEXE = ocxdlgap.def
OBJEXE = ocxdlgap.obj ocxdlg.obj

CFLAGS =-D_OCFPCH
SYSTEM=WIN32
OSMAJOR = 4
OSMINOR = 0
MODELS=dft
!if !$d(MODEL)
 MODEL=f
!endif

!include $(BCEXAMPLEDIR)\owlocfmk.gen
