#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1995, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS=ftd
SYSTEMS=WIN32
EXERES=animctl
OBJEXE=animctlx.obj

!include $(BCEXAMPLEDIR)\owlmake.gen

