#----------------------------------------------------------------------------
# ObjectWindows - (C) Copyright 1991, 1993 by Borland International
#----------------------------------------------------------------------------

EXERES = help
HLP    = help
HLP_   = help.rtf
!include $(BCEXAMPLEDIR)\owlmake.gen
