#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1993, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES = layout
OBJEXE = layout.obj laydia.obj
MODELS = ldft

!include $(BCEXAMPLEDIR)\owlmake.gen
