#----------------------------------------------------------------------------
# Borland C++ (C) Copyright 1995 by Borland International
#   examples\series\blandmdi\makefile
#----------------------------------------------------------------------------

SYSTEMS = WIN16 WIN32
OSMAJOR = 4
OSMINOR = 0
EXERES  = blandmdi
CPCH    = -H"windows.h" -H=blandmdi.csm
OBJEXE  = blandmdi.obj winmain.obj init.obj about.obj dispatch.obj misc.obj\
          mdichild.obj

!include $(BCEXAMPLEDIR)\makefile.gen
